name: Build packages
description: Build all koobiq packages
runs:
  using: composite
  steps:
    - name: Build packages
      shell: bash
      run: .github/workflows/actions/build-packages/entrypoint.sh
