/**
 ******************************************************************************
 * DO NOT MANUALLY EDIT THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED.
 ******************************************************************************
 */

import { Type } from '@angular/core';

/** Loads the component of the example with the given id, or resolves to `undefined` for an unknown id. */
export async function loadExampleComponent(id: string): Promise<Type<unknown> | undefined> {
    switch (id) {
        case 'accordion-content':
            return import('@koobiq/docs-examples/components/accordion').then((m) => m.AccordionContentExample);
        case 'accordion-header':
            return import('@koobiq/docs-examples/components/accordion').then((m) => m.AccordionHeaderExample);
        case 'accordion-in-panel':
            return import('@koobiq/docs-examples/components/accordion').then((m) => m.AccordionInPanelExample);
        case 'accordion-in-section':
            return import('@koobiq/docs-examples/components/accordion').then((m) => m.AccordionInSectionExample);
        case 'accordion-inactive-section':
            return import('@koobiq/docs-examples/components/accordion').then((m) => m.AccordionInactiveSectionExample);
        case 'accordion-interactive-elements':
            return import('@koobiq/docs-examples/components/accordion').then((m) => m.AccordionInteractiveElementsExample);
        case 'accordion-overview':
            return import('@koobiq/docs-examples/components/accordion').then((m) => m.AccordionOverviewExample);
        case 'accordion-sections':
            return import('@koobiq/docs-examples/components/accordion').then((m) => m.AccordionSectionsExample);
        case 'accordion-state-saving':
            return import('@koobiq/docs-examples/components/accordion').then((m) => m.AccordionStateSavingExample);
        case 'accordion-states':
            return import('@koobiq/docs-examples/components/accordion').then((m) => m.AccordionStatesExample);
        case 'actions-panel-adaptive':
            return import('@koobiq/docs-examples/components/actions-panel').then((m) => m.ActionsPanelAdaptiveExample);
        case 'actions-panel-close':
            return import('@koobiq/docs-examples/components/actions-panel').then((m) => m.ActionsPanelCloseExample);
        case 'actions-panel-custom-counter':
            return import('@koobiq/docs-examples/components/actions-panel').then((m) => m.ActionsPanelCustomCounterExample);
        case 'actions-panel-global':
            return import('@koobiq/docs-examples/components/actions-panel').then((m) => m.ActionsPanelGlobalExample);
        case 'actions-panel-overview':
            return import('@koobiq/docs-examples/components/actions-panel').then((m) => m.ActionsPanelOverviewExample);
        case 'actions-panel-with-dropdown-and-popover':
            return import('@koobiq/docs-examples/components/actions-panel').then((m) => m.ActionsPanelWithDropdownAndPopoverExample);
        case 'ag-grid-and-actions-panel':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridAndActionsPanelExample);
        case 'ag-grid-and-content-panel':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridAndContentPanelExample);
        case 'ag-grid-column-menu':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridColumnMenuExample);
        case 'ag-grid-column-state':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridColumnStateExample);
        case 'ag-grid-copy-selected':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridCopySelectedExample);
        case 'ag-grid-export':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridExportExample);
        case 'ag-grid-external-filter-state':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridExternalFilterStateExample);
        case 'ag-grid-filter-state':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridFilterStateExample);
        case 'ag-grid-infinite-selection':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridInfiniteSelectionExample);
        case 'ag-grid-loading-overlay':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridLoadingOverlayExample);
        case 'ag-grid-overview':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridOverviewExample);
        case 'ag-grid-quick-filter-state':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridQuickFilterStateExample);
        case 'ag-grid-row-actions':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridRowActionsExample);
        case 'ag-grid-row-dragging':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridRowDraggingExample);
        case 'ag-grid-row-focus-state':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridRowFocusStateExample);
        case 'ag-grid-row-group':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridRowGroupExample);
        case 'ag-grid-row-selection-state':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridRowSelectionStateExample);
        case 'ag-grid-skeleton-cell-renderer':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridSkeletonCellRendererExample);
        case 'ag-grid-status-bar':
            return import('@koobiq/docs-examples/components/ag-grid').then((m) => m.AgGridStatusBarExample);
        case 'alert-close':
            return import('@koobiq/docs-examples/components/alert').then((m) => m.AlertCloseExample);
        case 'alert-content':
            return import('@koobiq/docs-examples/components/alert').then((m) => m.AlertContentExample);
        case 'alert-dynamic':
            return import('@koobiq/docs-examples/components/alert').then((m) => m.AlertDynamicExample);
        case 'alert-overview':
            return import('@koobiq/docs-examples/components/alert').then((m) => m.AlertOverviewExample);
        case 'alert-status':
            return import('@koobiq/docs-examples/components/alert').then((m) => m.AlertStatusExample);
        case 'alert-variants':
            return import('@koobiq/docs-examples/components/alert').then((m) => m.AlertVariantsExample);
        case 'app-switcher-overview':
            return import('@koobiq/docs-examples/components/app-switcher').then((m) => m.AppSwitcherOverviewExample);
        case 'app-switcher-sites':
            return import('@koobiq/docs-examples/components/app-switcher').then((m) => m.AppSwitcherSitesExample);
        case 'autocomplete-overview':
            return import('@koobiq/docs-examples/components/autocomplete').then((m) => m.AutocompleteOverviewExample);
        case 'autocomplete-search-smart':
            return import('@koobiq/docs-examples/components/autocomplete').then((m) => m.AutocompleteSearchSmartExample);
        case 'autocomplete-with-footer':
            return import('@koobiq/docs-examples/components/autocomplete').then((m) => m.AutocompleteWithFooterExample);
        case 'badge-content':
            return import('@koobiq/docs-examples/components/badge').then((m) => m.BadgeContentExample);
        case 'badge-list':
            return import('@koobiq/docs-examples/components/badge').then((m) => m.BadgeListExample);
        case 'badge-overview':
            return import('@koobiq/docs-examples/components/badge').then((m) => m.BadgeOverviewExample);
        case 'badge-size':
            return import('@koobiq/docs-examples/components/badge').then((m) => m.BadgeSizeExample);
        case 'badge-table':
            return import('@koobiq/docs-examples/components/badge').then((m) => m.BadgeTableExample);
        case 'badge-tooltip':
            return import('@koobiq/docs-examples/components/badge').then((m) => m.BadgeTooltipExample);
        case 'breadcrumbs-custom-template':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsCustomTemplateExample);
        case 'breadcrumbs-dropdown':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsDropdownExample);
        case 'breadcrumbs-overview':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsOverviewExample);
        case 'breadcrumbs-routing':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsRoutingExample);
        case 'breadcrumbs-selectable-text':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsSelectableTextExample);
        case 'breadcrumbs-size':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsSizeExample);
        case 'breadcrumbs-truncate-by-abbrev-items':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsTruncateByAbbrevItemsExample);
        case 'breadcrumbs-truncate-center-items':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsTruncateCenterItemsExample);
        case 'breadcrumbs-truncate-head-items':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsTruncateHeadItemsExample);
        case 'breadcrumbs-truncate-tail-items':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsTruncateTailItemsExample);
        case 'breadcrumbs-with-auto-wrap-adaptive':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsWithAutoWrapAdaptiveExample);
        case 'breadcrumbs-with-wrap':
            return import('@koobiq/docs-examples/components/breadcrumbs').then((m) => m.BreadcrumbsWithWrapExample);
        case 'button-toggle-alignment-overview':
            return import('@koobiq/docs-examples/components/button-toggle').then((m) => m.ButtonToggleAlignmentOverviewExample);
        case 'button-toggle-disabled-all-overview':
            return import('@koobiq/docs-examples/components/button-toggle').then((m) => m.ButtonToggleDisabledAllOverviewExample);
        case 'button-toggle-disabled-partial-overview':
            return import('@koobiq/docs-examples/components/button-toggle').then((m) => m.ButtonToggleDisabledPartialOverviewExample);
        case 'button-toggle-overview':
            return import('@koobiq/docs-examples/components/button-toggle').then((m) => m.ButtonToggleOverviewExample);
        case 'button-toggle-tooltip-overview':
            return import('@koobiq/docs-examples/components/button-toggle').then((m) => m.ButtonToggleTooltipOverviewExample);
        case 'button-content':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonContentExample);
        case 'button-fill-and-style-only-icon':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonFillAndStyleOnlyIconExample);
        case 'button-fill-and-style':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonFillAndStyleExample);
        case 'button-fill-content':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonFillContentExample);
        case 'button-fixed-content':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonFixedContentExample);
        case 'button-group-content':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonGroupContentExample);
        case 'button-group-custom-content':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonGroupCustomContentExample);
        case 'button-group-overview':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonGroupOverviewExample);
        case 'button-group-style':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonGroupStyleExample);
        case 'button-group-vertical':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonGroupVerticalExample);
        case 'button-hug-content':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonHugContentExample);
        case 'button-loading-state':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonLoadingStateExample);
        case 'button-overview':
            return import('@koobiq/docs-examples/components/button').then((m) => m.ButtonOverviewExample);
        case 'block-checkbox':
            return import('@koobiq/docs-examples/components/checkbox').then((m) => m.BlockCheckboxExample);
        case 'checkbox-indeterminate':
            return import('@koobiq/docs-examples/components/checkbox').then((m) => m.CheckboxIndeterminateExample);
        case 'checkbox-multiline':
            return import('@koobiq/docs-examples/components/checkbox').then((m) => m.CheckboxMultilineExample);
        case 'checkbox-overview':
            return import('@koobiq/docs-examples/components/checkbox').then((m) => m.CheckboxOverviewExample);
        case 'pseudo-checkbox':
            return import('@koobiq/docs-examples/components/checkbox').then((m) => m.PseudoCheckboxExample);
        case 'clamped-list-dotted':
            return import('@koobiq/docs-examples/components/clamped-text').then((m) => m.ClampedListDottedExample);
        case 'clamped-list-overview':
            return import('@koobiq/docs-examples/components/clamped-text').then((m) => m.ClampedListOverviewExample);
        case 'clamped-list':
            return import('@koobiq/docs-examples/components/clamped-text').then((m) => m.ClampedListExample);
        case 'clamped-text-external-state':
            return import('@koobiq/docs-examples/components/clamped-text').then((m) => m.ClampedTextExternalStateExample);
        case 'clamped-text-overview':
            return import('@koobiq/docs-examples/components/clamped-text').then((m) => m.ClampedTextOverviewExample);
        case 'code-block-header-pinned':
            return import('@koobiq/docs-examples/components/code-block').then((m) => m.CodeBlockHeaderPinnedExample);
        case 'code-block-overview':
            return import('@koobiq/docs-examples/components/code-block').then((m) => m.CodeBlockOverviewExample);
        case 'code-block-with-custom-locale-configuration':
            return import('@koobiq/docs-examples/components/code-block').then((m) => m.CodeBlockWithCustomLocaleConfigurationExample);
        case 'code-block-with-filled':
            return import('@koobiq/docs-examples/components/code-block').then((m) => m.CodeBlockWithFilledExample);
        case 'code-block-with-link':
            return import('@koobiq/docs-examples/components/code-block').then((m) => m.CodeBlockWithLinkExample);
        case 'code-block-with-max-height':
            return import('@koobiq/docs-examples/components/code-block').then((m) => m.CodeBlockWithMaxHeightExample);
        case 'code-block-with-no-border':
            return import('@koobiq/docs-examples/components/code-block').then((m) => m.CodeBlockWithNoBorderExample);
        case 'code-block-with-soft-wrap':
            return import('@koobiq/docs-examples/components/code-block').then((m) => m.CodeBlockWithSoftWrapExample);
        case 'code-block-with-tabs-and-shadow':
            return import('@koobiq/docs-examples/components/code-block').then((m) => m.CodeBlockWithTabsAndShadowExample);
        case 'code-block-with-tabs':
            return import('@koobiq/docs-examples/components/code-block').then((m) => m.CodeBlockWithTabsExample);
        case 'content-panel-overview':
            return import('@koobiq/docs-examples/components/content-panel').then((m) => m.ContentPanelOverviewExample);
        case 'content-panel-state-saving':
            return import('@koobiq/docs-examples/components/content-panel').then((m) => m.ContentPanelStateSavingExample);
        case 'theme-css-variables':
            return import('@koobiq/docs-examples/components/core').then((m) => m.ThemeCssVariablesExample);
        case 'theme-static-selection':
            return import('@koobiq/docs-examples/components/core').then((m) => m.ThemeStaticSelectionExample);
        case 'absolute-date-formatter':
            return import('@koobiq/docs-examples/components/date-formatter').then((m) => m.AbsoluteDateFormatterExample);
        case 'date-formatter-special-use':
            return import('@koobiq/docs-examples/components/date-formatter').then((m) => m.DateFormatterSpecialUseExample);
        case 'date-formatter-typical-use':
            return import('@koobiq/docs-examples/components/date-formatter').then((m) => m.DateFormatterTypicalUseExample);
        case 'duration-date-formatter':
            return import('@koobiq/docs-examples/components/date-formatter').then((m) => m.DurationDateFormatterExample);
        case 'range-date-formatter':
            return import('@koobiq/docs-examples/components/date-formatter').then((m) => m.RangeDateFormatterExample);
        case 'relative-date-formatter':
            return import('@koobiq/docs-examples/components/date-formatter').then((m) => m.RelativeDateFormatterExample);
        case 'datepicker-and-timepicker':
            return import('@koobiq/docs-examples/components/datepicker').then((m) => m.DatepickerAndTimepickerExample);
        case 'datepicker-inactive':
            return import('@koobiq/docs-examples/components/datepicker').then((m) => m.DatepickerInactiveExample);
        case 'datepicker-minimax':
            return import('@koobiq/docs-examples/components/datepicker').then((m) => m.DatepickerMinimaxExample);
        case 'datepicker-overview':
            return import('@koobiq/docs-examples/components/datepicker').then((m) => m.DatepickerOverviewExample);
        case 'datepicker-range':
            return import('@koobiq/docs-examples/components/datepicker').then((m) => m.DatepickerRangeExample);
        case 'datepicker-required':
            return import('@koobiq/docs-examples/components/datepicker').then((m) => m.DatepickerRequiredExample);
        case 'divider-overview':
            return import('@koobiq/docs-examples/components/divider').then((m) => m.DividerOverviewExample);
        case 'divider-vertical':
            return import('@koobiq/docs-examples/components/divider').then((m) => m.DividerVerticalExample);
        case 'dl-horizontal-overview':
            return import('@koobiq/docs-examples/components/dl').then((m) => m.DlHorizontalOverviewExample);
        case 'dl-long-text':
            return import('@koobiq/docs-examples/components/dl').then((m) => m.DlLongTextExample);
        case 'dl-overview':
            return import('@koobiq/docs-examples/components/dl').then((m) => m.DlOverviewExample);
        case 'dl-resizable':
            return import('@koobiq/docs-examples/components/dl').then((m) => m.DlResizableExample);
        case 'dl-small':
            return import('@koobiq/docs-examples/components/dl').then((m) => m.DlSmallExample);
        case 'dl-vertical-overview':
            return import('@koobiq/docs-examples/components/dl').then((m) => m.DlVerticalOverviewExample);
        case 'dropdown-disabled':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownDisabledExample);
        case 'dropdown-item-action':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownItemActionExample);
        case 'dropdown-item-link':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownItemLinkExample);
        case 'dropdown-item-progress':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownItemProgressExample);
        case 'dropdown-lazyload-data':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownLazyloadDataExample);
        case 'dropdown-navigation-wrap':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownNavigationWrapExample);
        case 'dropdown-nested':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownNestedExample);
        case 'dropdown-open-by-arrow-down':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownOpenByArrowDownExample);
        case 'dropdown-overview':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownOverviewExample);
        case 'dropdown-recursive-template':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownRecursiveTemplateExample);
        case 'dropdown-safe-area':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownSafeAreaExample);
        case 'dropdown-with-filter':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownWithFilterExample);
        case 'dropdown-with-footer':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownWithFooterExample);
        case 'dropdown-x-position':
            return import('@koobiq/docs-examples/components/dropdown').then((m) => m.DropdownXPositionExample);
        case 'dynamic-translation-overview':
            return import('@koobiq/docs-examples/components/dynamic-translation').then((m) => m.DynamicTranslationOverviewExample);
        case 'dynamic-translation-with-dynamic-component-creation':
            return import('@koobiq/docs-examples/components/dynamic-translation').then((m) => m.DynamicTranslationWithDynamicComponentCreationExample);
        case 'empty-state-actions':
            return import('@koobiq/docs-examples/components/empty-state').then((m) => m.EmptyStateActionsExample);
        case 'empty-state-actions2':
            return import('@koobiq/docs-examples/components/empty-state').then((m) => m.EmptyStateActions2Example);
        case 'empty-state-align':
            return import('@koobiq/docs-examples/components/empty-state').then((m) => m.EmptyStateAlignExample);
        case 'empty-state-big':
            return import('@koobiq/docs-examples/components/empty-state').then((m) => m.EmptyStateBigExample);
        case 'empty-state-content':
            return import('@koobiq/docs-examples/components/empty-state').then((m) => m.EmptyStateContentExample);
        case 'empty-state-error':
            return import('@koobiq/docs-examples/components/empty-state').then((m) => m.EmptyStateErrorExample);
        case 'empty-state-icon':
            return import('@koobiq/docs-examples/components/empty-state').then((m) => m.EmptyStateIconExample);
        case 'empty-state-overview':
            return import('@koobiq/docs-examples/components/empty-state').then((m) => m.EmptyStateOverviewExample);
        case 'empty-state-size':
            return import('@koobiq/docs-examples/components/empty-state').then((m) => m.EmptyStateSizeExample);
        case 'empty-state-text-only':
            return import('@koobiq/docs-examples/components/empty-state').then((m) => m.EmptyStateTextOnlyExample);
        case 'empty-state-title':
            return import('@koobiq/docs-examples/components/empty-state').then((m) => m.EmptyStateTitleExample);
        case 'file-upload-allowed':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadAllowedExample);
        case 'file-upload-custom-text-via-input':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadCustomTextViaInputExample);
        case 'file-upload-cva-overview':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadCvaOverviewExample);
        case 'file-upload-dropzone':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadDropzoneExample);
        case 'file-upload-indeterminate-loading-overview':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadIndeterminateLoadingOverviewExample);
        case 'file-upload-local-dropzone':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadLocalDropzoneExample);
        case 'file-upload-multiple-accept-validation':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleAcceptValidationExample);
        case 'file-upload-multiple-add-strategy':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleAddStrategyExample);
        case 'file-upload-multiple-compact-overview':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleCompactOverviewExample);
        case 'file-upload-multiple-custom-text-overview':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleCustomTextOverviewExample);
        case 'file-upload-multiple-default-overview':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleDefaultOverviewExample);
        case 'file-upload-multiple-default-validation-reactive-forms-overview':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleDefaultValidationReactiveFormsOverviewExample);
        case 'file-upload-multiple-disabled':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleDisabledExample);
        case 'file-upload-multiple-error-filled':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleErrorFilledExample);
        case 'file-upload-multiple-error':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleErrorExample);
        case 'file-upload-multiple-mixed-validation':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleMixedValidationExample);
        case 'file-upload-multiple-required-reactive-validation':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleRequiredReactiveValidationExample);
        case 'file-upload-multiple-with-custom-icon':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleWithCustomIconExample);
        case 'file-upload-multiple-with-fixed-height':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleWithFixedHeightExample);
        case 'file-upload-multiple-with-max-height':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadMultipleWithMaxHeightExample);
        case 'file-upload-overview':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadOverviewExample);
        case 'file-upload-primitive':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadPrimitiveExample);
        case 'file-upload-single-accept-validation':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadSingleAcceptValidationExample);
        case 'file-upload-single-async-validation':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadSingleAsyncValidationExample);
        case 'file-upload-single-mixed-validation':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadSingleMixedValidationExample);
        case 'file-upload-single-required-reactive-validation':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadSingleRequiredReactiveValidationExample);
        case 'file-upload-single-validation-reactive-forms-overview':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadSingleValidationReactiveFormsOverviewExample);
        case 'file-upload-single-with-signal':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadSingleWithSignalExample);
        case 'file-upload-single-with-size':
            return import('@koobiq/docs-examples/components/file-upload').then((m) => m.FileUploadSingleWithSizeExample);
        case 'filesize-formatter-overview':
            return import('@koobiq/docs-examples/components/filesize-formatter').then((m) => m.FilesizeFormatterOverviewExample);
        case 'filesize-formatter-table-number':
            return import('@koobiq/docs-examples/components/filesize-formatter').then((m) => m.FilesizeFormatterTableNumberExample);
        case 'filter-bar-cleanable':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarCleanableExample);
        case 'filter-bar-complete-functions':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarCompleteFunctionsExample);
        case 'filter-bar-custom-pipe':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarCustomPipeExample);
        case 'filter-bar-date-limits':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarDateLimitsExample);
        case 'filter-bar-inactive-filter':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarInactiveFilterExample);
        case 'filter-bar-localization':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarLocalizationExample);
        case 'filter-bar-locked-options':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarLockedOptionsExample);
        case 'filter-bar-master-checkbox':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarMasterCheckboxExample);
        case 'filter-bar-option-caption':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarOptionCaptionExample);
        case 'filter-bar-overview':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarOverviewExample);
        case 'filter-bar-panel-max-height':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarPanelMaxHeightExample);
        case 'filter-bar-pipe-types':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarPipeTypesExample);
        case 'filter-bar-readonly-pipe':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarReadonlyPipeExample);
        case 'filter-bar-readonly-pipes':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarReadonlyPipesExample);
        case 'filter-bar-removable':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarRemovableExample);
        case 'filter-bar-required':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarRequiredExample);
        case 'filter-bar-saved-filters':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarSavedFiltersExample);
        case 'filter-bar-search-in-pipes':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarSearchInPipesExample);
        case 'filter-bar-search':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarSearchExample);
        case 'filter-bar-state-saving':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarStateSavingExample);
        case 'filter-bar-uniq-pipes':
            return import('@koobiq/docs-examples/components/filter-bar').then((m) => m.FilterBarUniqPipesExample);
        case 'flag-aspect-ratio':
            return import('@koobiq/docs-examples/components/flag').then((m) => m.FlagAspectRatioExample);
        case 'flag-circle':
            return import('@koobiq/docs-examples/components/flag').then((m) => m.FlagCircleExample);
        case 'flag-fallback':
            return import('@koobiq/docs-examples/components/flag').then((m) => m.FlagFallbackExample);
        case 'flag-language':
            return import('@koobiq/docs-examples/components/flag').then((m) => m.FlagLanguageExample);
        case 'flag-overview':
            return import('@koobiq/docs-examples/components/flag').then((m) => m.FlagOverviewExample);
        case 'flag-sizes':
            return import('@koobiq/docs-examples/components/flag').then((m) => m.FlagSizesExample);
        case 'flag-square':
            return import('@koobiq/docs-examples/components/flag').then((m) => m.FlagSquareExample);
        case 'flag-stylized':
            return import('@koobiq/docs-examples/components/flag').then((m) => m.FlagStylizedExample);
        case 'form-field-horizontal':
            return import('@koobiq/docs-examples/components/form-field').then((m) => m.FormFieldHorizontalExample);
        case 'form-field-overview':
            return import('@koobiq/docs-examples/components/form-field').then((m) => m.FormFieldOverviewExample);
        case 'form-field-password-overview':
            return import('@koobiq/docs-examples/components/form-field').then((m) => m.FormFieldPasswordOverviewExample);
        case 'form-field-with-cleaner':
            return import('@koobiq/docs-examples/components/form-field').then((m) => m.FormFieldWithCleanerExample);
        case 'form-field-with-custom-error-state-matcher-set-by-attribute':
            return import('@koobiq/docs-examples/components/form-field').then((m) => m.FormFieldWithCustomErrorStateMatcherSetByAttributeExample);
        case 'form-field-with-custom-error-state-matcher-set-by-dependency-injection-provider':
            return import('@koobiq/docs-examples/components/form-field').then((m) => m.FormFieldWithCustomErrorStateMatcherSetByDependencyInjectionProviderExample);
        case 'form-field-with-error':
            return import('@koobiq/docs-examples/components/form-field').then((m) => m.FormFieldWithErrorExample);
        case 'form-field-with-hint':
            return import('@koobiq/docs-examples/components/form-field').then((m) => m.FormFieldWithHintExample);
        case 'form-field-with-prefix-and-suffix':
            return import('@koobiq/docs-examples/components/form-field').then((m) => m.FormFieldWithPrefixAndSuffixExample);
        case 'form-field-without-borders':
            return import('@koobiq/docs-examples/components/form-field').then((m) => m.FormFieldWithoutBordersExample);
        case 'form-fieldset-invalid':
            return import('@koobiq/docs-examples/components/forms').then((m) => m.FormFieldsetInvalidExample);
        case 'form-fieldset-overview':
            return import('@koobiq/docs-examples/components/forms').then((m) => m.FormFieldsetOverviewExample);
        case 'form-fieldset-with-button':
            return import('@koobiq/docs-examples/components/forms').then((m) => m.FormFieldsetWithButtonExample);
        case 'horizontal-form-labels':
            return import('@koobiq/docs-examples/components/forms').then((m) => m.HorizontalFormLabelsExample);
        case 'horizontal-form':
            return import('@koobiq/docs-examples/components/forms').then((m) => m.HorizontalFormExample);
        case 'vertical-form':
            return import('@koobiq/docs-examples/components/forms').then((m) => m.VerticalFormExample);
        case 'highlight-background-complex':
            return import('@koobiq/docs-examples/components/highlight').then((m) => m.HighlightBackgroundComplexExample);
        case 'highlight-background-table':
            return import('@koobiq/docs-examples/components/highlight').then((m) => m.HighlightBackgroundTableExample);
        case 'highlight-background':
            return import('@koobiq/docs-examples/components/highlight').then((m) => m.HighlightBackgroundExample);
        case 'highlight-select':
            return import('@koobiq/docs-examples/components/highlight').then((m) => m.HighlightSelectExample);
        case 'icon-button-custom-size':
            return import('@koobiq/docs-examples/components/icon').then((m) => m.IconButtonCustomSizeExample);
        case 'icon-button-overview':
            return import('@koobiq/docs-examples/components/icon').then((m) => m.IconButtonOverviewExample);
        case 'icon-button-size':
            return import('@koobiq/docs-examples/components/icon').then((m) => m.IconButtonSizeExample);
        case 'icon-button-style':
            return import('@koobiq/docs-examples/components/icon').then((m) => m.IconButtonStyleExample);
        case 'icon-item-color':
            return import('@koobiq/docs-examples/components/icon').then((m) => m.IconItemColorExample);
        case 'icon-item-overview':
            return import('@koobiq/docs-examples/components/icon').then((m) => m.IconItemOverviewExample);
        case 'icon-item-size':
            return import('@koobiq/docs-examples/components/icon').then((m) => m.IconItemSizeExample);
        case 'icon-item-variant':
            return import('@koobiq/docs-examples/components/icon').then((m) => m.IconItemVariantExample);
        case 'inline-edit-content-alignment':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditContentAlignmentExample);
        case 'inline-edit-controls':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditControlsExample);
        case 'inline-edit-custom-handler':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditCustomHandlerExample);
        case 'inline-edit-customized-design':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditCustomizedDesignExample);
        case 'inline-edit-date-time':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditDateTimeExample);
        case 'inline-edit-disabled':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditDisabledExample);
        case 'inline-edit-editable-header':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditEditableHeaderExample);
        case 'inline-edit-horizontal-list':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditHorizontalListExample);
        case 'inline-edit-menu':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditMenuExample);
        case 'inline-edit-on-clean':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditOnCleanExample);
        case 'inline-edit-overview':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditOverviewExample);
        case 'inline-edit-select-basic':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditSelectBasicExample);
        case 'inline-edit-select-multiline':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditSelectMultilineExample);
        case 'inline-edit-select':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditSelectExample);
        case 'inline-edit-unfilled':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditUnfilledExample);
        case 'inline-edit-validation':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditValidationExample);
        case 'inline-edit-vertical-list':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditVerticalListExample);
        case 'inline-edit-without-label':
            return import('@koobiq/docs-examples/components/inline-edit').then((m) => m.InlineEditWithoutLabelExample);
        case 'input-number-overview':
            return import('@koobiq/docs-examples/components/input').then((m) => m.InputNumberOverviewExample);
        case 'input-overview':
            return import('@koobiq/docs-examples/components/input').then((m) => m.InputOverviewExample);
        case 'input-password-overview':
            return import('@koobiq/docs-examples/components/input').then((m) => m.InputPasswordOverviewExample);
        case 'input-with-mask':
            return import('@koobiq/docs-examples/components/input').then((m) => m.InputWithMaskExample);
        case 'layout-flex-alignment':
            return import('@koobiq/docs-examples/components/layout-flex').then((m) => m.LayoutFlexAlignmentExample);
        case 'layout-flex-behaviour-modifiers':
            return import('@koobiq/docs-examples/components/layout-flex').then((m) => m.LayoutFlexBehaviourModifiersExample);
        case 'layout-flex-offsets':
            return import('@koobiq/docs-examples/components/layout-flex').then((m) => m.LayoutFlexOffsetsExample);
        case 'layout-flex-order':
            return import('@koobiq/docs-examples/components/layout-flex').then((m) => m.LayoutFlexOrderExample);
        case 'layout-flex-overview':
            return import('@koobiq/docs-examples/components/layout-flex').then((m) => m.LayoutFlexOverviewExample);
        case 'link-application':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkApplicationExample);
        case 'link-caption':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkCaptionExample);
        case 'link-disabled':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkDisabledExample);
        case 'link-external':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkExternalExample);
        case 'link-general':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkGeneralExample);
        case 'link-icons':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkIconsExample);
        case 'link-multi-line':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkMultiLineExample);
        case 'link-overview':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkOverviewExample);
        case 'link-prepositions':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkPrepositionsExample);
        case 'link-print':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkPrintExample);
        case 'link-pseudo':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkPseudoExample);
        case 'link-target-blank':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkTargetBlankExample);
        case 'link-visited':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkVisitedExample);
        case 'link-with-caption':
            return import('@koobiq/docs-examples/components/link').then((m) => m.LinkWithCaptionExample);
        case 'list-action-button':
            return import('@koobiq/docs-examples/components/list').then((m) => m.ListActionButtonExample);
        case 'list-draggable-connected':
            return import('@koobiq/docs-examples/components/list').then((m) => m.ListDraggableConnectedExample);
        case 'list-draggable-handle':
            return import('@koobiq/docs-examples/components/list').then((m) => m.ListDraggableHandleExample);
        case 'list-draggable':
            return import('@koobiq/docs-examples/components/list').then((m) => m.ListDraggableExample);
        case 'list-groups':
            return import('@koobiq/docs-examples/components/list').then((m) => m.ListGroupsExample);
        case 'list-intermediate-state':
            return import('@koobiq/docs-examples/components/list').then((m) => m.ListIntermediateStateExample);
        case 'list-multiple-checkbox':
            return import('@koobiq/docs-examples/components/list').then((m) => m.ListMultipleCheckboxExample);
        case 'list-multiple-keyboard':
            return import('@koobiq/docs-examples/components/list').then((m) => m.ListMultipleKeyboardExample);
        case 'list-overview':
            return import('@koobiq/docs-examples/components/list').then((m) => m.ListOverviewExample);
        case 'list-select-all':
            return import('@koobiq/docs-examples/components/list').then((m) => m.ListSelectAllExample);
        case 'list-virtual-scroll':
            return import('@koobiq/docs-examples/components/list').then((m) => m.ListVirtualScrollExample);
        case 'loader-overlay-background':
            return import('@koobiq/docs-examples/components/loader-overlay').then((m) => m.LoaderOverlayBackgroundExample);
        case 'loader-overlay-default':
            return import('@koobiq/docs-examples/components/loader-overlay').then((m) => m.LoaderOverlayDefaultExample);
        case 'loader-overlay-fixed-top':
            return import('@koobiq/docs-examples/components/loader-overlay').then((m) => m.LoaderOverlayFixedTopExample);
        case 'loader-overlay-large':
            return import('@koobiq/docs-examples/components/loader-overlay').then((m) => m.LoaderOverlayLargeExample);
        case 'loader-overlay-overview':
            return import('@koobiq/docs-examples/components/loader-overlay').then((m) => m.LoaderOverlayOverviewExample);
        case 'loader-overlay-size':
            return import('@koobiq/docs-examples/components/loader-overlay').then((m) => m.LoaderOverlaySizeExample);
        case 'markdown-article':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownArticleExample);
        case 'markdown-code-block':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownCodeBlockExample);
        case 'markdown-code':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownCodeExample);
        case 'markdown-divider':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownDividerExample);
        case 'markdown-headers-combinations':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownHeadersCombinationsExample);
        case 'markdown-image':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownImageExample);
        case 'markdown-line-break-with-markdown-text-input':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownLineBreakWithMarkdownTextInputExample);
        case 'markdown-line-break':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownLineBreakExample);
        case 'markdown-link':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownLinkExample);
        case 'markdown-list':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownListExample);
        case 'markdown-overview':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownOverviewExample);
        case 'markdown-paragraph':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownParagraphExample);
        case 'markdown-quote':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownQuoteExample);
        case 'markdown-selection':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownSelectionExample);
        case 'markdown-table':
            return import('@koobiq/docs-examples/components/markdown').then((m) => m.MarkdownTableExample);
        case 'modal-caption':
            return import('@koobiq/docs-examples/components/modal').then((m) => m.ModalCaptionExample);
        case 'modal-component-with-injector':
            return import('@koobiq/docs-examples/components/modal').then((m) => m.ModalComponentWithInjectorExample);
        case 'modal-component':
            return import('@koobiq/docs-examples/components/modal').then((m) => m.ModalComponentExample);
        case 'modal-full-custom':
            return import('@koobiq/docs-examples/components/modal').then((m) => m.ModalFullCustomExample);
        case 'modal-multiple':
            return import('@koobiq/docs-examples/components/modal').then((m) => m.ModalMultipleExample);
        case 'modal-overview':
            return import('@koobiq/docs-examples/components/modal').then((m) => m.ModalOverviewExample);
        case 'modal-scroll':
            return import('@koobiq/docs-examples/components/modal').then((m) => m.ModalScrollExample);
        case 'modal-sizes':
            return import('@koobiq/docs-examples/components/modal').then((m) => m.ModalSizesExample);
        case 'modal-template':
            return import('@koobiq/docs-examples/components/modal').then((m) => m.ModalTemplateExample);
        case 'navbar-app-long-name':
            return import('@koobiq/docs-examples/components/navbar').then((m) => m.NavbarAppLongNameExample);
        case 'navbar-overview':
            return import('@koobiq/docs-examples/components/navbar').then((m) => m.NavbarOverviewExample);
        case 'navbar-template-outlet':
            return import('@koobiq/docs-examples/components/navbar').then((m) => m.NavbarTemplateOutletExample);
        case 'navbar-vertical-app-long-name':
            return import('@koobiq/docs-examples/components/navbar').then((m) => m.NavbarVerticalAppLongNameExample);
        case 'navbar-vertical-open-over':
            return import('@koobiq/docs-examples/components/navbar').then((m) => m.NavbarVerticalOpenOverExample);
        case 'navbar-vertical':
            return import('@koobiq/docs-examples/components/navbar').then((m) => m.NavbarVerticalExample);
        case 'notification-center-empty':
            return import('@koobiq/docs-examples/components/notification-center').then((m) => m.NotificationCenterEmptyExample);
        case 'notification-center-error':
            return import('@koobiq/docs-examples/components/notification-center').then((m) => m.NotificationCenterErrorExample);
        case 'notification-center-infinite-scroll':
            return import('@koobiq/docs-examples/components/notification-center').then((m) => m.NotificationCenterInfiniteScrollExample);
        case 'notification-center-overview':
            return import('@koobiq/docs-examples/components/notification-center').then((m) => m.NotificationCenterOverviewExample);
        case 'notification-center-popover':
            return import('@koobiq/docs-examples/components/notification-center').then((m) => m.NotificationCenterPopoverExample);
        case 'notification-center-push':
            return import('@koobiq/docs-examples/components/notification-center').then((m) => m.NotificationCenterPushExample);
        case 'number-formatter-locale':
            return import('@koobiq/docs-examples/components/number-formatter').then((m) => m.NumberFormatterLocaleExample);
        case 'number-formatter-overview':
            return import('@koobiq/docs-examples/components/number-formatter').then((m) => m.NumberFormatterOverviewExample);
        case 'number-formatter-rounding':
            return import('@koobiq/docs-examples/components/number-formatter').then((m) => m.NumberFormatterRoundingExample);
        case 'overflow-items-as-clamped-list':
            return import('@koobiq/docs-examples/components/overflow-items').then((m) => m.OverflowItemsAsClampedListExample);
        case 'overflow-items-justify-content':
            return import('@koobiq/docs-examples/components/overflow-items').then((m) => m.OverflowItemsJustifyContentExample);
        case 'overflow-items-overview':
            return import('@koobiq/docs-examples/components/overflow-items').then((m) => m.OverflowItemsOverviewExample);
        case 'overflow-items-with-always-visible-item':
            return import('@koobiq/docs-examples/components/overflow-items').then((m) => m.OverflowItemsWithAlwaysVisibleItemExample);
        case 'overflow-items-with-order':
            return import('@koobiq/docs-examples/components/overflow-items').then((m) => m.OverflowItemsWithOrderExample);
        case 'overflow-items-with-vertical-orientation':
            return import('@koobiq/docs-examples/components/overflow-items').then((m) => m.OverflowItemsWithVerticalOrientationExample);
        case 'popover-arrow-and-offset':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverArrowAndOffsetExample);
        case 'popover-arrowless':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverArrowlessExample);
        case 'popover-close':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverCloseExample);
        case 'popover-content':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverContentExample);
        case 'popover-header':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverHeaderExample);
        case 'popover-height':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverHeightExample);
        case 'popover-hover':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverHoverExample);
        case 'popover-overview':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverOverviewExample);
        case 'popover-paddings':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverPaddingsExample);
        case 'popover-placement-center':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverPlacementCenterExample);
        case 'popover-placement-edges':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverPlacementEdgesExample);
        case 'popover-scroll':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverScrollExample);
        case 'popover-scrolling-and-layering-page':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverScrollingAndLayeringPageExample);
        case 'popover-scrolling-and-layering':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverScrollingAndLayeringExample);
        case 'popover-small':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverSmallExample);
        case 'popover-width':
            return import('@koobiq/docs-examples/components/popover').then((m) => m.PopoverWidthExample);
        case 'progress-bar-indeterminate':
            return import('@koobiq/docs-examples/components/progress-bar').then((m) => m.ProgressBarIndeterminateExample);
        case 'progress-bar-overview':
            return import('@koobiq/docs-examples/components/progress-bar').then((m) => m.ProgressBarOverviewExample);
        case 'progress-spinner-indeterminate':
            return import('@koobiq/docs-examples/components/progress-spinner').then((m) => m.ProgressSpinnerIndeterminateExample);
        case 'progress-spinner-overview':
            return import('@koobiq/docs-examples/components/progress-spinner').then((m) => m.ProgressSpinnerOverviewExample);
        case 'radio-content':
            return import('@koobiq/docs-examples/components/radio').then((m) => m.RadioContentExample);
        case 'radio-group':
            return import('@koobiq/docs-examples/components/radio').then((m) => m.RadioGroupExample);
        case 'radio-multiline':
            return import('@koobiq/docs-examples/components/radio').then((m) => m.RadioMultilineExample);
        case 'radio-overview':
            return import('@koobiq/docs-examples/components/radio').then((m) => m.RadioOverviewExample);
        case 'radio-style':
            return import('@koobiq/docs-examples/components/radio').then((m) => m.RadioStyleExample);
        case 'resizer-overview':
            return import('@koobiq/docs-examples/components/resizer').then((m) => m.ResizerOverviewExample);
        case 'native-scrollbar':
            return import('@koobiq/docs-examples/components/scrollbar').then((m) => m.NativeScrollbarExample);
        case 'scrollbar-overview':
            return import('@koobiq/docs-examples/components/scrollbar').then((m) => m.ScrollbarOverviewExample);
        case 'scrollbar-scroll-to':
            return import('@koobiq/docs-examples/components/scrollbar').then((m) => m.ScrollbarScrollToExample);
        case 'scrollbar-virtual-scroll':
            return import('@koobiq/docs-examples/components/scrollbar').then((m) => m.ScrollbarVirtualScrollExample);
        case 'search-expandable-in-header':
            return import('@koobiq/docs-examples/components/search-expandable').then((m) => m.SearchExpandableInHeaderExample);
        case 'search-expandable-overview':
            return import('@koobiq/docs-examples/components/search-expandable').then((m) => m.SearchExpandableOverviewExample);
        case 'select-add-new-option':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectAddNewOptionExample);
        case 'select-auto-hide-scroll-strategy':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectAutoHideScrollStrategyExample);
        case 'select-cleaner-with-disabled':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectCleanerWithDisabledExample);
        case 'select-custom-matcher':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectCustomMatcherExample);
        case 'select-custom-tag-content':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectCustomTagContentExample);
        case 'select-custom-trigger':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectCustomTriggerExample);
        case 'select-disabled':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectDisabledExample);
        case 'select-footer':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectFooterExample);
        case 'select-groups':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectGroupsExample);
        case 'select-height':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectHeightExample);
        case 'select-icon':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectIconExample);
        case 'select-loading-error-custom':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectLoadingErrorCustomExample);
        case 'select-loading-error':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectLoadingErrorExample);
        case 'select-loading':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectLoadingExample);
        case 'select-locale-configuration':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectLocaleConfigurationExample);
        case 'select-multiple':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectMultipleExample);
        case 'select-no-variants':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectNoVariantsExample);
        case 'select-overview':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectOverviewExample);
        case 'select-paging-error':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectPagingErrorExample);
        case 'select-paging':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectPagingExample);
        case 'select-preselected-values':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectPreselectedValuesExample);
        case 'select-prioritized-selected':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectPrioritizedSelectedExample);
        case 'select-scrolling-and-layering-page':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectScrollingAndLayeringPageExample);
        case 'select-scrolling-and-layering':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectScrollingAndLayeringExample);
        case 'select-search':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectSearchExample);
        case 'select-select-all-label':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectSelectAllLabelExample);
        case 'select-select-all':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectSelectAllExample);
        case 'select-two-line-option':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectTwoLineOptionExample);
        case 'select-validation':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectValidationExample);
        case 'select-virtual-scroll':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectVirtualScrollExample);
        case 'select-with-multiline-matcher':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectWithMultilineMatcherExample);
        case 'select-with-panel-min-width':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectWithPanelMinWidthExample);
        case 'select-with-panel-width-auto':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectWithPanelWidthAutoExample);
        case 'select-with-panel-width-default':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectWithPanelWidthDefaultExample);
        case 'select-with-panel-width-fixed':
            return import('@koobiq/docs-examples/components/select').then((m) => m.SelectWithPanelWidthFixedExample);
        case 'sidebar-overview':
            return import('@koobiq/docs-examples/components/sidebar').then((m) => m.SidebarOverviewExample);
        case 'sidebar-state-saving':
            return import('@koobiq/docs-examples/components/sidebar').then((m) => m.SidebarStateSavingExample);
        case 'sidebar-with-splitter':
            return import('@koobiq/docs-examples/components/sidebar').then((m) => m.SidebarWithSplitterExample);
        case 'sidepanel-disable-close':
            return import('@koobiq/docs-examples/components/sidepanel').then((m) => m.SidepanelDisableCloseExample);
        case 'sidepanel-normal-mode':
            return import('@koobiq/docs-examples/components/sidepanel').then((m) => m.SidepanelNormalModeExample);
        case 'sidepanel-overlayed':
            return import('@koobiq/docs-examples/components/sidepanel').then((m) => m.SidepanelOverlayedExample);
        case 'sidepanel-overview':
            return import('@koobiq/docs-examples/components/sidepanel').then((m) => m.SidepanelOverviewExample);
        case 'sidepanel-sizes':
            return import('@koobiq/docs-examples/components/sidepanel').then((m) => m.SidepanelSizesExample);
        case 'sidepanel-state-saving':
            return import('@koobiq/docs-examples/components/sidepanel').then((m) => m.SidepanelStateSavingExample);
        case 'sidepanel-with-custom-injector':
            return import('@koobiq/docs-examples/components/sidepanel').then((m) => m.SidepanelWithCustomInjectorExample);
        case 'sidepanel-with-dynamic-config-update':
            return import('@koobiq/docs-examples/components/sidepanel').then((m) => m.SidepanelWithDynamicConfigUpdateExample);
        case 'skeleton-directive':
            return import('@koobiq/docs-examples/components/skeleton').then((m) => m.SkeletonDirectiveExample);
        case 'skeleton-in-sidepanel':
            return import('@koobiq/docs-examples/components/skeleton').then((m) => m.SkeletonInSidepanelExample);
        case 'skeleton-overview':
            return import('@koobiq/docs-examples/components/skeleton').then((m) => m.SkeletonOverviewExample);
        case 'split-button-content':
            return import('@koobiq/docs-examples/components/split-button').then((m) => m.SplitButtonContentExample);
        case 'split-button-disabled-state':
            return import('@koobiq/docs-examples/components/split-button').then((m) => m.SplitButtonDisabledStateExample);
        case 'split-button-menu-width':
            return import('@koobiq/docs-examples/components/split-button').then((m) => m.SplitButtonMenuWidthExample);
        case 'split-button-overview':
            return import('@koobiq/docs-examples/components/split-button').then((m) => m.SplitButtonOverviewExample);
        case 'split-button-progress-state':
            return import('@koobiq/docs-examples/components/split-button').then((m) => m.SplitButtonProgressStateExample);
        case 'split-button-styles':
            return import('@koobiq/docs-examples/components/split-button').then((m) => m.SplitButtonStylesExample);
        case 'split-button-text-overflow':
            return import('@koobiq/docs-examples/components/split-button').then((m) => m.SplitButtonTextOverflowExample);
        case 'splitter-appearance':
            return import('@koobiq/docs-examples/components/splitter').then((m) => m.SplitterAppearanceExample);
        case 'splitter-collapsible':
            return import('@koobiq/docs-examples/components/splitter').then((m) => m.SplitterCollapsibleExample);
        case 'splitter-constraints':
            return import('@koobiq/docs-examples/components/splitter').then((m) => m.SplitterConstraintsExample);
        case 'splitter-disabled':
            return import('@koobiq/docs-examples/components/splitter').then((m) => m.SplitterDisabledExample);
        case 'splitter-nested':
            return import('@koobiq/docs-examples/components/splitter').then((m) => m.SplitterNestedExample);
        case 'splitter-orientation':
            return import('@koobiq/docs-examples/components/splitter').then((m) => m.SplitterOrientationExample);
        case 'splitter-overview':
            return import('@koobiq/docs-examples/components/splitter').then((m) => m.SplitterOverviewExample);
        case 'splitter-snap':
            return import('@koobiq/docs-examples/components/splitter').then((m) => m.SplitterSnapExample);
        case 'table-disable-hover':
            return import('@koobiq/docs-examples/components/table').then((m) => m.TableDisableHoverExample);
        case 'table-full-width':
            return import('@koobiq/docs-examples/components/table').then((m) => m.TableFullWidthExample);
        case 'table-overview':
            return import('@koobiq/docs-examples/components/table').then((m) => m.TableOverviewExample);
        case 'table-sticky-header':
            return import('@koobiq/docs-examples/components/table').then((m) => m.TableStickyHeaderExample);
        case 'table-with-borders':
            return import('@koobiq/docs-examples/components/table').then((m) => m.TableWithBordersExample);
        case 'tabs-actionbar':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsActionbarExample);
        case 'tabs-active-tab-id':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsActiveTabIdExample);
        case 'tabs-active-tab-index':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsActiveTabIndexExample);
        case 'tabs-add-tab-vertical':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsAddTabVerticalExample);
        case 'tabs-add-tab':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsAddTabExample);
        case 'tabs-custom-label':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsCustomLabelExample);
        case 'tabs-disabled':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsDisabledExample);
        case 'tabs-empty-label':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsEmptyLabelExample);
        case 'tabs-nav-bar-overview':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsNavBarOverviewExample);
        case 'tabs-overview':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsOverviewExample);
        case 'tabs-state-saving':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsStateSavingExample);
        case 'tabs-stretch':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsStretchExample);
        case 'tabs-underlined':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsUnderlinedExample);
        case 'tabs-vertical-icons':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsVerticalIconsExample);
        case 'tabs-vertical':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsVerticalExample);
        case 'tabs-with-scroll-vertical':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsWithScrollVerticalExample);
        case 'tabs-with-scroll':
            return import('@koobiq/docs-examples/components/tabs').then((m) => m.TabsWithScrollExample);
        case 'tag-autocomplete-cleaner-with-disabled':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagAutocompleteCleanerWithDisabledExample);
        case 'tag-autocomplete-draggable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagAutocompleteDraggableExample);
        case 'tag-autocomplete-editable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagAutocompleteEditableExample);
        case 'tag-autocomplete-onpaste-off':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagAutocompleteOnpasteOffExample);
        case 'tag-autocomplete-option-operations':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagAutocompleteOptionOperationsExample);
        case 'tag-autocomplete-overview':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagAutocompleteOverviewExample);
        case 'tag-autocomplete-removable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagAutocompleteRemovableExample);
        case 'tag-autocomplete-search':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagAutocompleteSearchExample);
        case 'tag-autocomplete-with-form-control-validators':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagAutocompleteWithFormControlValidatorsExample);
        case 'tag-disabled':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagDisabledExample);
        case 'tag-editable-with-validation':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagEditableWithValidationExample);
        case 'tag-editable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagEditableExample);
        case 'tag-fill-and-style':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagFillAndStyleExample);
        case 'tag-input-cleaner-with-disabled':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagInputCleanerWithDisabledExample);
        case 'tag-input-draggable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagInputDraggableExample);
        case 'tag-input-editable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagInputEditableExample);
        case 'tag-input-onpaste-off':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagInputOnpasteOffExample);
        case 'tag-input-overview':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagInputOverviewExample);
        case 'tag-input-removable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagInputRemovableExample);
        case 'tag-input-with-form-control-validators':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagInputWithFormControlValidatorsExample);
        case 'tag-list-draggable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagListDraggableExample);
        case 'tag-list-editable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagListEditableExample);
        case 'tag-list-overview':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagListOverviewExample);
        case 'tag-list-removable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagListRemovableExample);
        case 'tag-long-text':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagLongTextExample);
        case 'tag-overview':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagOverviewExample);
        case 'tag-removable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagRemovableExample);
        case 'tag-selectable':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagSelectableExample);
        case 'tag-with-icon':
            return import('@koobiq/docs-examples/components/tags').then((m) => m.TagWithIconExample);
        case 'textarea-can-grow':
            return import('@koobiq/docs-examples/components/textarea').then((m) => m.TextareaCanGrowExample);
        case 'textarea-disabled':
            return import('@koobiq/docs-examples/components/textarea').then((m) => m.TextareaDisabledExample);
        case 'textarea-error-state':
            return import('@koobiq/docs-examples/components/textarea').then((m) => m.TextareaErrorStateExample);
        case 'textarea-max-rows':
            return import('@koobiq/docs-examples/components/textarea').then((m) => m.TextareaMaxRowsExample);
        case 'textarea-overview':
            return import('@koobiq/docs-examples/components/textarea').then((m) => m.TextareaOverviewExample);
        case 'time-range-as-form-field':
            return import('@koobiq/docs-examples/components/time-range').then((m) => m.TimeRangeAsFormFieldExample);
        case 'time-range-custom-option':
            return import('@koobiq/docs-examples/components/time-range').then((m) => m.TimeRangeCustomOptionExample);
        case 'time-range-custom-range-types':
            return import('@koobiq/docs-examples/components/time-range').then((m) => m.TimeRangeCustomRangeTypesExample);
        case 'time-range-custom-trigger':
            return import('@koobiq/docs-examples/components/time-range').then((m) => m.TimeRangeCustomTriggerExample);
        case 'time-range-empty-type-list':
            return import('@koobiq/docs-examples/components/time-range').then((m) => m.TimeRangeEmptyTypeListExample);
        case 'time-range-min-max':
            return import('@koobiq/docs-examples/components/time-range').then((m) => m.TimeRangeMinMaxExample);
        case 'time-range-overview':
            return import('@koobiq/docs-examples/components/time-range').then((m) => m.TimeRangeOverviewExample);
        case 'timepicker-field-validation':
            return import('@koobiq/docs-examples/components/timepicker').then((m) => m.TimepickerFieldValidationExample);
        case 'timepicker-overview':
            return import('@koobiq/docs-examples/components/timepicker').then((m) => m.TimepickerOverviewExample);
        case 'timepicker-variations':
            return import('@koobiq/docs-examples/components/timepicker').then((m) => m.TimepickerVariationsExample);
        case 'timezone-overview':
            return import('@koobiq/docs-examples/components/timezone').then((m) => m.TimezoneOverviewExample);
        case 'timezone-search-overview':
            return import('@koobiq/docs-examples/components/timezone').then((m) => m.TimezoneSearchOverviewExample);
        case 'timezone-trigger-overview':
            return import('@koobiq/docs-examples/components/timezone').then((m) => m.TimezoneTriggerOverviewExample);
        case 'title-custom-content':
            return import('@koobiq/docs-examples/components/title').then((m) => m.TitleCustomContentExample);
        case 'title-list-option':
            return import('@koobiq/docs-examples/components/title').then((m) => m.TitleListOptionExample);
        case 'title-multiple-text':
            return import('@koobiq/docs-examples/components/title').then((m) => m.TitleMultipleTextExample);
        case 'title-overview':
            return import('@koobiq/docs-examples/components/title').then((m) => m.TitleOverviewExample);
        case 'title-vertical-overflow':
            return import('@koobiq/docs-examples/components/title').then((m) => m.TitleVerticalOverflowExample);
        case 'toast-actions-overview':
            return import('@koobiq/docs-examples/components/toast').then((m) => m.ToastActionsOverviewExample);
        case 'toast-hide-overview':
            return import('@koobiq/docs-examples/components/toast').then((m) => m.ToastHideOverviewExample);
        case 'toast-link-overview':
            return import('@koobiq/docs-examples/components/toast').then((m) => m.ToastLinkOverviewExample);
        case 'toast-multiline':
            return import('@koobiq/docs-examples/components/toast').then((m) => m.ToastMultilineExample);
        case 'toast-overview':
            return import('@koobiq/docs-examples/components/toast').then((m) => m.ToastOverviewExample);
        case 'toast-progress-bar-overview':
            return import('@koobiq/docs-examples/components/toast').then((m) => m.ToastProgressBarOverviewExample);
        case 'toast-report-overview':
            return import('@koobiq/docs-examples/components/toast').then((m) => m.ToastReportOverviewExample);
        case 'toast-types-overview':
            return import('@koobiq/docs-examples/components/toast').then((m) => m.ToastTypesOverviewExample);
        case 'toast-user-data':
            return import('@koobiq/docs-examples/components/toast').then((m) => m.ToastUserDataExample);
        case 'toggle-disabled':
            return import('@koobiq/docs-examples/components/toggle').then((m) => m.ToggleDisabledExample);
        case 'toggle-error':
            return import('@koobiq/docs-examples/components/toggle').then((m) => m.ToggleErrorExample);
        case 'toggle-indeterminate':
            return import('@koobiq/docs-examples/components/toggle').then((m) => m.ToggleIndeterminateExample);
        case 'toggle-label-left':
            return import('@koobiq/docs-examples/components/toggle').then((m) => m.ToggleLabelLeftExample);
        case 'toggle-loading':
            return import('@koobiq/docs-examples/components/toggle').then((m) => m.ToggleLoadingExample);
        case 'toggle-multiline':
            return import('@koobiq/docs-examples/components/toggle').then((m) => m.ToggleMultilineExample);
        case 'toggle-overview':
            return import('@koobiq/docs-examples/components/toggle').then((m) => m.ToggleOverviewExample);
        case 'toggle-with-hint':
            return import('@koobiq/docs-examples/components/toggle').then((m) => m.ToggleWithHintExample);
        case 'tooltip-arrow':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipArrowExample);
        case 'tooltip-disabled-for-component':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipDisabledForComponentExample);
        case 'tooltip-disabled':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipDisabledExample);
        case 'tooltip-dynamic':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipDynamicExample);
        case 'tooltip-extended':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipExtendedExample);
        case 'tooltip-hide-with-timeout':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipHideWithTimeoutExample);
        case 'tooltip-interactive':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipInteractiveExample);
        case 'tooltip-offset':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipOffsetExample);
        case 'tooltip-overview':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipOverviewExample);
        case 'tooltip-placements':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipPlacementsExample);
        case 'tooltip-relative-to-caret':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipRelativeToCaretExample);
        case 'tooltip-relative-to-pointer':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipRelativeToPointerExample);
        case 'tooltip-style':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipStyleExample);
        case 'tooltip-wide-width':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipWideWidthExample);
        case 'tooltip-width':
            return import('@koobiq/docs-examples/components/tooltip').then((m) => m.TooltipWidthExample);
        case 'top-bar-actions':
            return import('@koobiq/docs-examples/components/top-bar').then((m) => m.TopBarActionsExample);
        case 'top-bar-breadcrumbs-adaptive':
            return import('@koobiq/docs-examples/components/top-bar').then((m) => m.TopBarBreadcrumbsAdaptiveExample);
        case 'top-bar-breadcrumbs':
            return import('@koobiq/docs-examples/components/top-bar').then((m) => m.TopBarBreadcrumbsExample);
        case 'top-bar-overflow':
            return import('@koobiq/docs-examples/components/top-bar').then((m) => m.TopBarOverflowExample);
        case 'top-bar-overview':
            return import('@koobiq/docs-examples/components/top-bar').then((m) => m.TopBarOverviewExample);
        case 'top-bar-title-counter-adaptive':
            return import('@koobiq/docs-examples/components/top-bar').then((m) => m.TopBarTitleCounterAdaptiveExample);
        case 'top-bar-title-counter':
            return import('@koobiq/docs-examples/components/top-bar').then((m) => m.TopBarTitleCounterExample);
        case 'tree-select-child-selection-overview':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectChildSelectionOverviewExample);
        case 'tree-select-cleaner-with-disabled':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectCleanerWithDisabledExample);
        case 'tree-select-custom-matcher-with-input':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectCustomMatcherWithInputExample);
        case 'tree-select-custom-matcher':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectCustomMatcherExample);
        case 'tree-select-custom-trigger':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectCustomTriggerExample);
        case 'tree-select-deleted-nodes':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectDeletedNodesExample);
        case 'tree-select-footer-overview':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectFooterOverviewExample);
        case 'tree-select-height':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectHeightExample);
        case 'tree-select-lazyload':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectLazyloadExample);
        case 'tree-select-multiple-overview':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectMultipleOverviewExample);
        case 'tree-select-overview':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectOverviewExample);
        case 'tree-select-search-overview':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectSearchOverviewExample);
        case 'tree-select-search-smart':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectSearchSmartExample);
        case 'tree-select-select-all-label':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectSelectAllLabelExample);
        case 'tree-select-select-all':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectSelectAllExample);
        case 'tree-select-two-line-option':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectTwoLineOptionExample);
        case 'tree-select-with-multiline-matcher':
            return import('@koobiq/docs-examples/components/tree-select').then((m) => m.TreeSelectWithMultilineMatcherExample);
        case 'tree-access-rights':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeAccessRightsExample);
        case 'tree-action-button':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeActionButtonExample);
        case 'tree-checked-filtering':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeCheckedFilteringExample);
        case 'tree-custom-filtering':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeCustomFilteringExample);
        case 'tree-descendants-subcategories':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeDescendantsSubcategoriesExample);
        case 'tree-filtering':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeFilteringExample);
        case 'tree-lazyload':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeLazyloadExample);
        case 'tree-multiple-checkbox':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeMultipleCheckboxExample);
        case 'tree-multiple-checklist':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeMultipleChecklistExample);
        case 'tree-multiple-keyboard':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeMultipleKeyboardExample);
        case 'tree-overview':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeOverviewExample);
        case 'tree-select-and-mark':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeSelectAndMarkExample);
        case 'tree-selection-separate-from-focus':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeSelectionSeparateFromFocusExample);
        case 'tree-state-saving':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeStateSavingExample);
        case 'tree-toggle-on-click':
            return import('@koobiq/docs-examples/components/tree').then((m) => m.TreeToggleOnClickExample);
        case 'username-as-link':
            return import('@koobiq/docs-examples/components/username').then((m) => m.UsernameAsLinkExample);
        case 'username-custom':
            return import('@koobiq/docs-examples/components/username').then((m) => m.UsernameCustomExample);
        case 'username-filter-bar-option':
            return import('@koobiq/docs-examples/components/username').then((m) => m.UsernameFilterBarOptionExample);
        case 'username-overview':
            return import('@koobiq/docs-examples/components/username').then((m) => m.UsernameOverviewExample);
        case 'username-playground':
            return import('@koobiq/docs-examples/components/username').then((m) => m.UsernamePlaygroundExample);
        case 'username-search':
            return import('@koobiq/docs-examples/components/username').then((m) => m.UsernameSearchExample);
        case 'validation-basic-multiple-validators':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationBasicMultipleValidatorsExample);
        case 'validation-basic-single-validator':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationBasicSingleValidatorExample);
        case 'validation-cross-field-async':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationCrossFieldAsyncExample);
        case 'validation-cross-field-dates':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationCrossFieldDatesExample);
        case 'validation-cross-field-password':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationCrossFieldPasswordExample);
        case 'validation-message-for-specific-field':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationMessageForSpecificFieldExample);
        case 'validation-message-global-with-links':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationMessageGlobalWithLinksExample);
        case 'validation-message-global':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationMessageGlobalExample);
        case 'validation-no-message':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationNoMessageExample);
        case 'validation-on-blur-filled':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationOnBlurFilledExample);
        case 'validation-on-blur':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationOnBlurExample);
        case 'validation-on-open':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationOnOpenExample);
        case 'validation-on-submit-custom-matcher':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationOnSubmitCustomMatcherExample);
        case 'validation-on-submit':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationOnSubmitExample);
        case 'validation-on-type':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationOnTypeExample);
        case 'validation-optional-label':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationOptionalLabelExample);
        case 'validation-required-label':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationRequiredLabelExample);
        case 'validation-tag-list':
            return import('@koobiq/docs-examples/components/validation').then((m) => m.ValidationTagListExample);
        default:
            return undefined;
    }
}
