import { JsonValue, workspaces } from '@angular-devkit/core';

export type KoobiqTheme = 'light' | 'dark' | 'auto';

/**
 * Builders that represent an application's browser bundle. `@angular/build:application` is the
 * builder generated by the current `@schematics/angular` `application` generator; the
 * `@angular-devkit/build-angular:*` names are kept for workspaces still on an older Angular CLI,
 * which this schematic's peer range still supports.
 */
const APPLICATION_BUILDERS = new Set<string>([
    '@angular/build:application',
    '@angular-devkit/build-angular:application',
    '@angular-devkit/build-angular:browser',
    '@angular-devkit/build-angular:browser-esbuild',
    // Nx (confirmed against a real Nx 23 workspace, which uses `@angular/build:application`
    // above directly) reused these webpack-based executor names, under both its old `@nrwl` npm
    // scope and its current `@nx` one, before it switched to the native Angular builders.
    '@nrwl/angular:webpack-browser',
    '@nx/angular:webpack-browser'
]);

const KOOBIQ_STATIC_STYLE_ENTRIES = [
    'node_modules/@koobiq/icons/fonts/kbq-icons.css',
    'node_modules/@koobiq/design-tokens/web/css-tokens.css',
    'node_modules/@koobiq/components/prebuilt-themes/theme.css'
];

const THEME_TOKENS_PATTERN = /^node_modules\/@koobiq\/design-tokens\/web\/css-tokens-(light|dark)\.css$/;

/**
 * The style entries documented in the installation guide, in the order they must be loaded.
 * `'auto'` includes both token files, since `KbqThemeService` switches between them at runtime —
 * a static `'light'`/`'dark'` choice only needs its own.
 */
export function getKoobiqStyleEntries(theme: KoobiqTheme): string[] {
    const [icons, tokens, prebuiltTheme] = KOOBIQ_STATIC_STYLE_ENTRIES;
    const themeTokens = theme === 'auto' ? [
                  'node_modules/@koobiq/design-tokens/web/css-tokens-light.css',
                  'node_modules/@koobiq/design-tokens/web/css-tokens-dark.css'
              ] : [`node_modules/@koobiq/design-tokens/web/css-tokens-${theme}.css`];

    return [icons, tokens, ...themeTokens, prebuiltTheme];
}

/**
 * Prepends the Koobiq style entries ahead of whatever is already in `existingStyles`, matching the
 * order documented in installation.md, where the app's own stylesheet comes last. Re-running with
 * the same theme is a no-op; re-running with a different theme swaps the `css-tokens-*.css`
 * entries instead of accumulating duplicates. Non-string entries (style-budget objects) and any
 * unrelated entries are preserved, untouched, in their original order.
 */
export function mergeKoobiqStyles(existingStyles: JsonValue[], theme: KoobiqTheme): JsonValue[] {
    const desired = getKoobiqStyleEntries(theme);
    const rest = existingStyles.filter((entry) => {
        if (typeof entry !== 'string') return true;

        return (
            !desired.includes(entry) &&
            !KOOBIQ_STATIC_STYLE_ENTRIES.includes(entry) &&
            !THEME_TOKENS_PATTERN.test(entry)
        );
    });

    return [...desired, ...rest];
}

/**
 * Resolves the workspace-root-relative path of a project's index.html, mirroring the
 * `@angular/build:application` builder's own default (`<sourceRoot>/index.html`) when the
 * `index` option isn't set explicitly.
 */
export function getIndexHtmlPath(
    project: workspaces.ProjectDefinition,
    buildTarget: workspaces.TargetDefinition
): string {
    const indexOption = buildTarget.options?.index;

    if (typeof indexOption === 'string') {
        return indexOption;
    }

    if (indexOption && typeof indexOption === 'object' && !Array.isArray(indexOption)) {
        const input = (indexOption as Record<string, JsonValue>).input;

        if (typeof input === 'string') {
            return input;
        }
    }

    const sourceRoot = project.sourceRoot ?? `${project.root}/src`;

    return `${sourceRoot}/index.html`;
}

export interface WiredProject {
    projectName: string;
    projectRoot: string;
    indexHtmlPath: string;
    /** Whether the project's `build` target is configured for SSR (a `server` entry point or `ssr` option). */
    isSsr: boolean;
}

/**
 * Whether a `build` target's `server`/`ssr` options indicate the project renders on the server —
 * `KbqThemeCookieStore` matters there, where `KbqThemeLocalStorageStore`'s default doesn't reach
 * the server render.
 */
function isSsrBuildTarget(buildTarget: workspaces.TargetDefinition): boolean {
    const { server, ssr } = buildTarget.options ?? {};

    return Boolean((typeof server === 'string' && server) || ssr === true || (ssr && typeof ssr === 'object'));
}

/**
 * Mutates `workspace` in place: for every project (optionally scoped to `projectName`) whose
 * `build` target uses a recognized application builder, merges the Koobiq style entries for
 * `theme` into its `styles` array. Returns per-project wiring info the caller uses to edit
 * index.html and the project's bootstrap file afterward.
 *
 * Only the target literally named `build` is touched — not `test` (Karma) or `serve` — keeping the
 * change's blast radius minimal.
 */
export function applyKoobiqWorkspaceStyles(
    workspace: workspaces.WorkspaceDefinition,
    theme: KoobiqTheme,
    projectName?: string
): WiredProject[] {
    const wired: WiredProject[] = [];

    for (const [name, project] of workspace.projects) {
        if (projectName && name !== projectName) continue;

        const buildTarget = project.targets.get('build');

        if (!buildTarget || !APPLICATION_BUILDERS.has(buildTarget.builder)) continue;

        const options = buildTarget.options ?? (buildTarget.options = {});
        const existingStyles = Array.isArray(options.styles) ? (options.styles as JsonValue[]) : [];

        options.styles = mergeKoobiqStyles(existingStyles, theme);

        wired.push({
            projectName: name,
            projectRoot: project.root,
            indexHtmlPath: getIndexHtmlPath(project, buildTarget),
            isSsr: isSsrBuildTarget(buildTarget)
        });
    }

    return wired;
}
