import { basename } from 'path';
import type { CompiledPage } from './compile-page';
import type { DocsPageSource } from './sources';

/** Source files of a compiled page. */
export interface EmittedPage {
    /** Path of the page module in the output directory, without an extension: `alert/alert.en.page`. */
    modulePath: string;
    /** Module of the page component, which exports it as `default`. */
    component: string;
    /** Template the component refers to with `templateUrl`. */
    template: string;
}

const toPascalCase = (value: string): string =>
    value
        .split('-')
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join('');

const indent = (text: string, depth: number): string => text.replace(/\n/g, `\n${' '.repeat(depth * 4)}`);

const renderImport = (names: string[], from: string): string =>
    `import { ${[...names].sort().join(', ')} } from '${from}';`;

export function emitPage(page: CompiledPage, source: DocsPageSource): EmittedPage {
    const fileName = `${basename(source.path, '.mdx')}.page`;
    const className = ['Docs', source.id, source.tab, source.locale, 'page'].map(toPascalCase).join('');
    const componentNamesByImportPath = new Map<string, string[]>();

    for (const { importPath, componentName } of page.examples) {
        componentNamesByImportPath.set(importPath, [
            ...(componentNamesByImportPath.get(importPath) ?? []),
            componentName
        ]);
    }

    const imports = [renderImport(['ChangeDetectionStrategy', 'Component', 'ViewEncapsulation'], '@angular/core')];
    const componentImports: string[] = [];
    const members: string[] = [];

    if (page.codeBlocks.length > 0) {
        imports.push(renderImport(['KbqCodeBlock', 'KbqCodeBlockFile'], '@koobiq/components/code-block'));
        componentImports.push('KbqCodeBlock');
        members.push(
            `protected readonly codeBlocks: KbqCodeBlockFile[] = ${indent(JSON.stringify(page.codeBlocks, null, 4), 1)};`
        );
    }

    if (page.examples.length > 0 || page.browserExamples.length > 0) {
        for (const [importPath, componentNames] of [...componentNamesByImportPath].sort(([a], [b]) =>
            a.localeCompare(b)
        )) {
            imports.push(renderImport(componentNames, `@koobiq/docs-examples/${importPath}`));
        }

        imports.push(
            renderImport(
                ['DocsLiveExampleViewerComponent'],
                'src/app/components/live-example-viewer/docs-live-example-viewer'
            )
        );
        componentImports.push('DocsLiveExampleViewerComponent');

        // An example that renders only in the browser is imported on demand: a static import would put its code,
        // AG Grid for one, into the page chunk that the route and hydration wait for.
        const loaders = page.browserExamples.map(
            ({ componentName, importPath }) =>
                `${componentName}: { load: () => import('@koobiq/docs-examples/${importPath}').then((m) => m.${componentName}) }`
        );

        members.push(
            `protected readonly examples = { ${[...page.examples.map(({ componentName }) => componentName), ...loaders].join(', ')} };`
        );
    }

    const component = [
        `/** Generated by tools/docs-pages from ${source.path}. Do not edit. */`,
        ...imports,
        '',
        '@Component({',
        `    imports: [${componentImports.join(', ')}],`,
        `    templateUrl: './${fileName}.html',`,
        '    changeDetection: ChangeDetectionStrategy.OnPush,',
        '    encapsulation: ViewEncapsulation.None,',
        `    host: { class: 'docs-page kbq-markdown' }`,
        '})',
        `export default class ${className} {`,
        ...members.map((member) => `    ${member}`),
        '}',
        ''
    ].join('\n');

    return { modulePath: `${source.id}/${fileName}`, component, template: `${page.template}\n` };
}

/** Emits the registry the docs app provides as `DOCS_PAGES` and looks compiled pages up in by `[id][tab][locale]`. */
export function emitPagesRegistry(pages: { source: DocsPageSource; modulePath: string }[]): string {
    const registry = new Map<string, Map<string, Map<string, string>>>();

    for (const { source, modulePath } of [...pages].sort((a, b) => a.source.path.localeCompare(b.source.path))) {
        const tabs = registry.get(source.id) ?? new Map<string, Map<string, string>>();
        const locales = tabs.get(source.tab) ?? new Map<string, string>();

        locales.set(source.locale, `() => import('./${modulePath}')`);
        tabs.set(source.tab, locales);
        registry.set(source.id, tabs);
    }

    const renderLevel = (entries: Map<string, unknown>, depth: number): string => {
        const padding = ' '.repeat((depth + 1) * 4);
        const lines = [...entries].map(([key, value]) => {
            const rendered = typeof value === 'string' ? value : renderLevel(value as Map<string, unknown>, depth + 1);

            return `${padding}'${key}': ${rendered}`;
        });

        return `{\n${lines.join(',\n')}\n${' '.repeat(depth * 4)}}`;
    };

    return [
        '/** Generated by tools/docs-pages. Do not edit. */',
        `import type { DocsPages } from 'src/app/services/page-resolver';`,
        '',
        `export const DOCS_COMPILED_PAGES: DocsPages = ${renderLevel(registry, 0)};`,
        ''
    ].join('\n');
}
