import * as fs from 'fs';
import * as path from 'path';
import { parseExampleFile } from './parse-example-file';
import { resolveLocalImportFiles } from './resolve-local-imports';

interface ExampleMetadata {
    /** Name of the example component. */
    componentName: string;
    /** Path to the source file that declares this example. */
    sourcePath: string;
    /** Path to the directory containing this example. */
    packagePath: string;
    /** Selector to match the component of this example. */
    selector: string;
    /** Unique id for this example. */
    id: string;
    /** Title of the example. */
    title: string;
    /** Files for this example. */
    files: string[];
    /** Files shared with other examples via relative imports (e.g. a data file kept as a
     *  single source of truth), needed to compile the example but not shown in the docs
     *  source viewer. */
    localImportFiles: string[];
    /** Path from which to import the example. */
    importPath: string;
}

interface AnalyzedExamples {
    exampleMetadata: ExampleMetadata[];
}

/** Inlines the example module template with the specified parsed data. */
function inlineExampleModuleTemplate(parsedData: AnalyzedExamples): string {
    const { exampleMetadata } = parsedData;
    const exampleComponents = exampleMetadata.reduce((result, data) => {
        if (result[data.id] !== undefined) {
            throw Error(`Multiple examples with the same id have been discovered: ${data.id}`);
        }

        result[data.id] = {
            packagePath: data.packagePath,
            title: data.title,
            componentName: data.componentName,
            files: data.files,
            localImportFiles: data.localImportFiles,
            selector: data.selector,
            primaryFile: path.basename(data.sourcePath),
            importPath: data.importPath
        };

        return result;
    }, {} as any);

    return fs
        .readFileSync(require.resolve('./example-module.template'), 'utf8')
        .replace(/\${exampleComponents}/g, JSON.stringify(exampleComponents, null, 2))
        .replace(/\${exampleIds}/g, exampleMetadata.map(({ id }) => `  | '${id}'`).join('\n'));
}

/**
 * Generates the loader of the example components. It is an entry point of its own: bundled with `EXAMPLE_COMPONENTS`,
 * it would reach every documentation page that shows live examples.
 */
function generateExampleLoader({ exampleMetadata }: AnalyzedExamples): string {
    return [
        '/**',
        ' ******************************************************************************',
        ' * DO NOT MANUALLY EDIT THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED.',
        ' ******************************************************************************',
        ' */',
        '',
        `import { Type } from '@angular/core';`,
        '',
        '/** Loads the component of the example with the given id, or resolves to `undefined` for an unknown id. */',
        'export async function loadExampleComponent(id: string): Promise<Type<unknown> | undefined> {',
        '    switch (id) {',
        ...exampleMetadata.flatMap(({ id, importPath, componentName }) => [
            `        case '${id}':`,
            `            return import('@koobiq/docs-examples/${importPath}').then((m) => m.${componentName});`
        ]),
        '        default:',
        '            return undefined;',
        '    }',
        '}',
        ''
    ].join('\n');
}

/** Converts a given camel-cased string to a dash-cased string. */
function convertToDashCase(name: string): string {
    name = name.replace(/[A-Z]/g, ' $&');
    name = name.toLowerCase().trim();

    return name.split(' ').join('-');
}

/**
 * Analyzes the examples by parsing the given TypeScript files in order to find
 * individual example modules and example metadata.
 */
function analyzeExamples(sourceFiles: string[], baseDir: string): AnalyzedExamples {
    const exampleMetadata: ExampleMetadata[] = [];

    for (const sourceFile of sourceFiles) {
        const relativePath = path.relative(baseDir, sourceFile).replace(/\\/g, '/');
        const packagePath = path.dirname(relativePath);
        const importPath = path.dirname(packagePath);

        // Avoid parsing non-example files.
        if (!path.basename(sourceFile, path.extname(sourceFile)).endsWith('-example')) {
            continue;
        }

        const sourceContent = fs.readFileSync(sourceFile, 'utf-8');
        const { primaryComponent, secondaryComponents } = parseExampleFile(sourceFile, sourceContent);

        if (primaryComponent) {
            // Generate a unique id for the component by converting the class name to dash-case.
            const exampleId = convertToDashCase(primaryComponent.componentName.replace('Example', ''));
            const example: ExampleMetadata = {
                sourcePath: relativePath,
                packagePath,
                id: exampleId,
                selector: primaryComponent.selector,
                componentName: primaryComponent.componentName,
                title: primaryComponent.title.trim(),
                files: [],
                localImportFiles: [],
                importPath
            };

            // For consistency, we expect the example component selector to match
            // the id of the example.
            const expectedSelector = `${exampleId}-example`;

            if (primaryComponent.selector !== expectedSelector) {
                throw Error(
                    `Example ${exampleId} uses selector: ${primaryComponent.selector}, ` +
                        `but expected: ${expectedSelector}`
                );
            }

            if (primaryComponent['styleUrl']) {
                throw Error(`Example ${exampleId} uses 'styleUrl', but expected 'styleUrls' `);
            }

            example.files.push(path.basename(relativePath));

            if (primaryComponent.templateUrl) {
                example.files.push(primaryComponent.templateUrl);
            }

            if (primaryComponent.styleUrls) {
                example.files.push(...primaryComponent.styleUrls);
            }

            if (secondaryComponents.length) {
                for (const meta of secondaryComponents) {
                    if (meta.templateUrl) {
                        example.files.push(meta.templateUrl);
                    }

                    if (meta.styleUrls) {
                        example.files.push(...meta.styleUrls);
                    }
                }
            }

            // Pick up source shared with other examples via relative imports (e.g. a data
            // file kept as a single source of truth), so it's included in the generated
            // StackBlitz project. Kept separate from `files` so it's not shown as a tab of
            // its own in the docs source viewer.
            example.localImportFiles.push(...resolveLocalImportFiles(baseDir, packagePath, example.files));

            // Ensure referenced files actually exist in the example.
            [...example.files, ...example.localImportFiles].forEach((f) =>
                assertReferencedExampleFileExists(baseDir, packagePath, f)
            );
            exampleMetadata.push(example);
        } else {
            throw Error(
                `Could not find a primary example component in ${sourceFile}. ` +
                    `Ensure that there's a component with an @title annotation.`
            );
        }
    }

    return { exampleMetadata };
}

/** Asserts that the given file exists for the specified example. */
function assertReferencedExampleFileExists(baseDir: string, examplePackagePath: string, relativePath: string) {
    if (!fs.existsSync(path.join(baseDir, examplePackagePath, relativePath))) {
        throw Error(`Example "${examplePackagePath}" references "${relativePath}", but file does not exist.`);
    }
}

/**
 * Generates the example module and the example loader from the given source files and writes them to the specified
 * output files.
 */
export function generateExampleModule(
    sourceFiles: string[],
    outputFile: string,
    loaderOutputFile: string,
    baseDir: string = path.dirname(outputFile)
) {
    const analysisData = analyzeExamples(sourceFiles, baseDir);

    // Both files are prettier-ignored, and `.editorconfig` requires a final newline for every tracked file, so nothing
    // else would put it back after a regeneration.
    fs.writeFileSync(outputFile, `${inlineExampleModuleTemplate(analysisData).trimEnd()}\n`);
    fs.writeFileSync(loaderOutputFile, generateExampleLoader(analysisData));
}
