name: CI

on:
  push:
    branches:
      - main
  pull_request: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: |
            yarn run build:cdk
            yarn run build:components
            yarn run build:angular-luxon-adapter
            yarn run build:angular-moment-adapter
            yarn run styles:built-all
            yarn run build:cli


  check-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install
        run: yarn install --immutable
      - name: Check API
        run: yarn run check-api

  unit:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install
        run: yarn install --immutable
      - name: Unit
        run: |
          yarn run unit:cdk

