import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { DocsApiEntryPoint } from '../../../apps/docs/src/app/components/api-page/api-page.types';
import { docsGetItems } from '../../../apps/docs/src/app/structure';
import { EntryCollection } from '../types';
import { DocEntry } from './entities';
import { getApiEntryPoint } from './entry-point';

// A sibling of `dist/docs-pages`, not a subdirectory of it: `tools/docs-pages`'s own generator recursively
// deletes anything under its output root that its latest run did not just write, which would otherwise
// wipe this generator's output on whichever of the two runs second.
const PAGES_DIR = join('dist', 'docs-pages-api');
const MANIFEST_DIR = join('dist', 'docs-content', 'api-manifest');

// A `paths`-mapped specifier, not relative: it resolves the same regardless of where the generated file lands,
// the way `tools/docs-pages`'s own generated registry already does.
const TYPES_MODULE = 'src/app/components/api-page/api-page.types';

/** Removes what the latest run did not write: the data and the manifest of a removed entry point. */
function removeStale(dir: string, written: Set<string>): void {
    for (const name of readdirSync(dir)) {
        if (!written.has(name)) rmSync(join(dir, name), { recursive: true, force: true });
    }
}

/** A module of the data of one entry point, typed so that the build checks it against what the page renders. */
const emitEntryPoint = (entryPoint: DocsApiEntryPoint): string => [
        `/** Generated by tools/api-gen from the JSDoc of "${entryPoint.path}". Do not edit. */`,
        `import type { DocsApiEntryPoint } from '${TYPES_MODULE}';`,
        '',
        `const entryPoint: DocsApiEntryPoint = ${JSON.stringify(entryPoint, null, 4)};`,
        '',
        'export default entryPoint;',
        ''
    ].join('\n');

/**
 * Registers each entry point under every `structure.ts` item id that shares its `apiId` (`button` and
 * `button-group` both point at the `button` entry point). JSDoc is English, so both locales show the same data.
 */
function emitRegistry(modules: Map<string, string>): string {
    const entries = docsGetItems()
        .filter((item) => item.hasApi && item.apiId && modules.has(item.apiId))
        .map((item) => `    '${item.id}': () => import('./${modules.get(item.apiId!)}')`);

    return [
        '/** Generated by tools/api-gen. Do not edit. */',
        `import type { DocsApiEntryPoints } from '${TYPES_MODULE}';`,
        '',
        'export const DOCS_COMPILED_API_PAGES: DocsApiEntryPoints = {',
        entries.join(',\n'),
        '};',
        ''
    ].join('\n');
}

/**
 * Writes the API of each entry point as the data its `/api` tab renders, with a registry that loads it by the
 * structure item, and persists each entry point's manifest as JSON: the input `tools/check-api-docs` and
 * `tools/generate-llms-txt.ts` read.
 */
export function generateApiPages(entryCollections: EntryCollection<DocEntry>[]): number {
    const files: Record<string, string> = {};
    const modules = new Map<string, string>();
    const manifests = new Set<string>();

    mkdirSync(MANIFEST_DIR, { recursive: true });

    for (const { moduleName, packagesApiInfo } of entryCollections) {
        for (const { packageName, entries } of packagesApiInfo) {
            const name = `${moduleName}-${packageName}`;

            files[`${name}.api.ts`] = emitEntryPoint(getApiEntryPoint(entries, moduleName, packageName));
            modules.set(packageName, `${name}.api`);

            writeFileSync(join(MANIFEST_DIR, `${name}.json`), JSON.stringify(entries, null, 4));
            manifests.add(`${name}.json`);
        }
    }

    // `check-api-docs` counts every manifest in the directory, so one left by a removed entry point would
    // pass locally and then fail CI, which starts from a clean one.
    removeStale(MANIFEST_DIR, manifests);

    mkdirSync(PAGES_DIR, { recursive: true });

    files['index.ts'] = emitRegistry(modules);

    for (const [name, content] of Object.entries(files)) writeFileSync(join(PAGES_DIR, name), content);

    removeStale(PAGES_DIR, new Set(Object.keys(files)));

    return modules.size;
}
