import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';
import { docsGetItems } from '../../../apps/docs/src/app/structure';
import { EntryCollection } from '../types';
import { DocEntry } from './entities';
import { getEntryPointContext } from './helpers';
import { getRenderable } from './processing';
import { EntryPointContext, renderEntryPointTemplates } from './templates';

// A sibling of `dist/docs-pages`, not a subdirectory of it: `tools/docs-pages`'s own generator recursively
// deletes anything under its output root that its latest run did not just write, which would otherwise
// wipe this generator's output on whichever of the two runs second.
const PAGES_DIR = join('dist', 'docs-pages-api');
const MANIFEST_DIR = join('dist', 'docs-content', 'api-manifest');

const toPascalCase = (value: string): string =>
    value
        .split('-')
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join('');

interface EmittedApiPage {
    packageName: string;
    modulePath: string;
    /** Generated files by name: the component module, the page template and the templates of its parts. */
    files: Record<string, string>;
}

const renderComponent = (config: {
    selector?: string;
    imports: string[];
    templateUrl: string;
    host: string;
    lang?: string;
}) => [
        '@Component({',
        ...(config.selector ? [`    selector: '${config.selector}',`] : []),
        `    imports: [${config.imports.join(', ')}],`,
        `    templateUrl: './${config.templateUrl}',`,
        '    changeDetection: ChangeDetectionStrategy.OnPush,',
        '    encapsulation: ViewEncapsulation.None,',
        `    host: { class: '${config.host}'${config.lang ? `, lang: '${config.lang}'` : ''} }`,
        '})'
    ].join('\n');

/** Removes what the latest run did not write: part templates of a page that shrank, the manifest of a removed entry point. */
function removeStale(dir: string, written: Set<string>): void {
    for (const name of readdirSync(dir)) {
        if (!written.has(name)) rmSync(join(dir, name), { recursive: true, force: true });
    }
}

function emitApiPage(moduleName: string, packageName: string, context: EntryPointContext): EmittedApiPage {
    const modulePath = `${moduleName}-${packageName}.api.page`;
    const className = ['Docs', moduleName, packageName, 'ApiPage'].map(toPascalCase).join('');
    const partSelector = (index: number) => `docs-${moduleName}-${packageName}-api-part-${index + 1}`;
    const { page, parts } = renderEntryPointTemplates(context, partSelector);
    const partClasses = parts.map((_, index) => `${className}Part${index + 1}`);
    const entryImports = ['KbqBadge', 'KbqCodeBlock'];

    const component = [
        `/** Generated by tools/api-gen from the "${packageName}" entry point of "${moduleName}". Do not edit. */`,
        `import { ChangeDetectionStrategy, Component, ViewEncapsulation } from '@angular/core';`,
        `import { KbqBadge } from '@koobiq/components/badge';`,
        `import { KbqCodeBlock } from '@koobiq/components/code-block';`,
        '',
        ...parts.flatMap((_, index) => [
            renderComponent({
                selector: partSelector(index),
                imports: entryImports,
                templateUrl: `${modulePath}.part-${index + 1}.html`,
                host: 'docs-api__part'
            }),
            `class ${partClasses[index]} {}`,
            ''
        ]),
        renderComponent({
            // Split into parts, the page itself keeps only the import line, a code block, above them.
            imports: parts.length
                ? [...(context.primaryExportName ? ['KbqCodeBlock'] : []), ...partClasses]
                : entryImports,
            templateUrl: `${modulePath}.html`,
            host: 'docs-page kbq-markdown',
            // JsDoc is English, and the `ru` locale serves the same page: say so to a screen reader.
            lang: 'en'
        }),
        `export default class ${className} {}`,
        ''
    ].join('\n');

    return {
        packageName,
        modulePath,
        files: {
            [`${modulePath}.ts`]: component,
            [`${modulePath}.html`]: `${page}\n`,
            ...Object.fromEntries(parts.map((part, index) => [`${modulePath}.part-${index + 1}.html`, `${part}\n`]))
        }
    };
}

/**
 * Registers each page under every `structure.ts` item id that shares its `apiId` (`button` and `button-group`
 * both point at the `button` entry point), for both locales — JsDoc text is English-only, so `en` and `ru`
 * resolve to the same compiled page.
 */
function emitApiPagesRegistry(pages: EmittedApiPage[]): string {
    const byApiId = new Map(pages.map((page) => [page.packageName, page]));
    const entries = docsGetItems()
        .filter((item) => item.hasApi && item.apiId && byApiId.has(item.apiId))
        .map((item) => {
            const loader = `() => import('./${byApiId.get(item.apiId!)!.modulePath}')`;

            return `    '${item.id}': { api: { en: ${loader}, ru: ${loader} } }`;
        });

    return [
        '/** Generated by tools/api-gen. Do not edit. */',
        // A `paths`-mapped specifier, not relative: it resolves the same regardless of where this file
        // lands, the way `tools/docs-pages`'s own generated registry already does.
        `import type { DocsPages } from 'src/app/services/page-resolver';`,
        '',
        `export const DOCS_COMPILED_API_PAGES: DocsPages = {`,
        entries.join(',\n'),
        '};',
        ''
    ].join('\n');
}

/**
 * Generates the Angular component that renders each entry point's `/api` tab — the same kind of generated
 * page `tools/docs-pages` compiles MDX into, registered the same way, so the route resolves either one
 * without knowing which generator produced it. Also persists each entry point's manifest as JSON, the input
 * `tools/check-api-docs` and `tools/generate-llms-txt.ts` read.
 */
export function generateApiPages(entryCollections: EntryCollection<DocEntry>[]): number {
    const pages: EmittedApiPage[] = [];
    const manifests = new Set<string>();

    mkdirSync(MANIFEST_DIR, { recursive: true });

    for (const collection of entryCollections) {
        for (const packageApiInfo of collection.packagesApiInfo) {
            const renderableEntries = packageApiInfo.entries.map(getRenderable);
            const context = getEntryPointContext(renderableEntries, collection.moduleName, packageApiInfo.packageName);
            const manifest = `${collection.moduleName}-${packageApiInfo.packageName}.json`;

            pages.push(emitApiPage(collection.moduleName, packageApiInfo.packageName, context));

            writeFileSync(join(MANIFEST_DIR, manifest), JSON.stringify(packageApiInfo.entries, null, 4));
            manifests.add(manifest);
        }
    }

    // `check-api-docs` counts every manifest in the directory, so one left by a removed entry point would
    // pass locally and then fail CI, which starts from a clean one.
    removeStale(MANIFEST_DIR, manifests);

    mkdirSync(PAGES_DIR, { recursive: true });

    const files: Record<string, string> = Object.assign(
        { 'index.ts': emitApiPagesRegistry(pages) },
        ...pages.map((page) => page.files)
    );

    for (const [name, content] of Object.entries(files)) writeFileSync(join(PAGES_DIR, name), content);

    removeStale(PAGES_DIR, new Set(Object.keys(files)));

    return pages.length;
}
