import { DateTime } from 'luxon';
import { DocsLocale } from './constants/locale';

export type DocsDocStructureCategoryItem = {
    id: string;
    name: Record<DocsLocale, string>;
    hasApi: boolean;
    hasExamples: boolean;
    isGuide?: boolean;
    apiId?: string;
    svgPreview?: string;
    /**
     * NOTE! Do not edit manually, this property is autogenerated.
     */
    categoryId?: string;
    /**
     * Indicates whether documentation item as "new".
     * Determined by comparing the current date with expiration date.
     */
    isNew?: boolean;
};

export enum DocsDocStructureCategoryId {
    Main = 'main',
    Components = 'components',
    Other = 'other',
    Icons = 'icons',
    CDK = 'cdk'
}

export type DocsDocStructureCategory = {
    id: DocsDocStructureCategoryId;
    name: Record<DocsLocale, string>;
    items: DocsDocStructureCategoryItem[];
    isPreviewed?: boolean;
};

export enum DocsDocStructureCategoryItemSection {
    Overview = 'overview',
    Api = 'api',
    Examples = 'examples'
}

export class DocsDocStructure {
    private static structure: Record<DocsDocStructureCategoryId, DocsDocStructureCategory[]> = this.makeStructure({
        [DocsDocStructureCategoryId.Main]: [
            {
                id: DocsDocStructureCategoryId.Main,
                name: {
                    ru: 'Основное',
                    en: 'Main'
                },
                isPreviewed: true,
                items: [
                    {
                        id: 'installation',
                        name: {
                            ru: 'Установка',
                            en: 'Installation'
                        },
                        svgPreview: 'install',
                        isGuide: true,
                        hasApi: false,
                        hasExamples: false
                    },
                    {
                        id: 'versioning',
                        name: {
                            ru: 'Версионирование',
                            en: 'Versioning'
                        },
                        svgPreview: 'versioning',
                        isGuide: true,
                        hasApi: false,
                        hasExamples: false
                    },
                    {
                        id: 'directory-structure',
                        name: {
                            ru: 'Структура каталогов',
                            en: 'Directory structure'
                        },
                        svgPreview: 'catalog structure',
                        isGuide: true,
                        hasApi: false,
                        hasExamples: false
                    },
                    {
                        id: 'theming',
                        name: {
                            ru: 'Темизация',
                            en: 'Theming'
                        },
                        svgPreview: 'themes',
                        isGuide: true,
                        hasApi: false,
                        hasExamples: false
                    },
                    {
                        id: 'typography',
                        name: {
                            ru: 'Типографика',
                            en: 'Typography'
                        },
                        svgPreview: 'typography',
                        hasApi: false,
                        hasExamples: false
                    },
                    {
                        id: 'design-tokens',
                        name: {
                            ru: 'Дизайн-токены',
                            en: 'Design tokens'
                        },
                        svgPreview: 'tokens',
                        hasApi: false,
                        hasExamples: false
                    },
                    {
                        id: 'schematics',
                        name: {
                            ru: 'Схематики',
                            en: 'Schematics'
                        },
                        svgPreview: 'schematics',
                        hasApi: false,
                        hasExamples: false
                    },

                    {
                        id: 'migration',
                        name: {
                            ru: 'Гайды по миграции',
                            en: 'Migration guides'
                        },
                        svgPreview: '',
                        hasApi: false,
                        hasExamples: false,
                        isNew: this.expiresAt('2025-07-13')
                    }
                ]
            }
        ],
        [DocsDocStructureCategoryId.Components]: [
            {
                id: DocsDocStructureCategoryId.Components,
                name: {
                    ru: 'Компоненты',
                    en: 'Components'
                },
                isPreviewed: true,
                items: [
                    {
                        id: 'accordion',
                        name: {
                            ru: 'Accordion',
                            en: 'Accordion'
                        },
                        svgPreview: 'accordion',
                        hasApi: true,
                        apiId: 'accordion',
                        hasExamples: false
                    },
                    {
                        id: 'actions-panel',
                        name: {
                            ru: 'Actions panel',
                            en: 'Actions panel'
                        },
                        svgPreview: 'actions-panel',
                        hasApi: true,
                        apiId: 'actions-panel',
                        hasExamples: false
                    },
                    {
                        id: 'ag-grid',
                        name: {
                            ru: 'AG grid',
                            en: 'AG grid'
                        },
                        svgPreview: 'ag-grid',
                        hasApi: false,
                        hasExamples: false,
                        isNew: this.expiresAt('2025-05-04')
                    },
                    {
                        id: 'alert',
                        name: {
                            ru: 'Alert',
                            en: 'Alert'
                        },
                        svgPreview: 'alerts',
                        hasApi: true,
                        apiId: 'alert',
                        hasExamples: false
                    },
                    {
                        id: 'autocomplete',
                        name: {
                            ru: 'Autocomplete',
                            en: 'Autocomplete'
                        },
                        svgPreview: 'autocomplete',
                        hasApi: true,
                        apiId: 'autocomplete',
                        hasExamples: false
                    },
                    {
                        id: 'badge',
                        name: {
                            ru: 'Badge',
                            en: 'Badge'
                        },
                        svgPreview: 'badges',
                        hasApi: true,
                        apiId: 'badge',
                        hasExamples: false
                    },
                    {
                        id: 'breadcrumbs',
                        name: {
                            ru: 'Breadcrumbs',
                            en: 'Breadcrumbs'
                        },
                        svgPreview: 'breadcrumbs',
                        hasApi: true,
                        apiId: 'breadcrumbs',
                        hasExamples: true
                    },
                    {
                        id: 'button',
                        name: {
                            ru: 'Button',
                            en: 'Button'
                        },
                        svgPreview: 'button',
                        hasApi: true,
                        apiId: 'button',
                        hasExamples: false
                    },
                    {
                        id: 'button-toggle',
                        name: {
                            ru: 'Button toggle',
                            en: 'Button toggle'
                        },
                        svgPreview: 'button toggle',
                        hasApi: true,
                        apiId: 'button-toggle',
                        hasExamples: false
                    },
                    {
                        id: 'checkbox',
                        name: {
                            ru: 'Checkbox',
                            en: 'Checkbox'
                        },
                        svgPreview: 'checkbox',
                        hasApi: true,
                        apiId: 'checkbox',
                        hasExamples: false
                    },
                    {
                        id: 'code-block',
                        name: {
                            ru: 'Code block',
                            en: 'Code block'
                        },
                        svgPreview: 'code-block',
                        hasApi: true,
                        apiId: 'code-block',
                        hasExamples: true
                    },
                    {
                        id: 'content-panel',
                        name: {
                            ru: 'Content panel',
                            en: 'Content panel'
                        },
                        svgPreview: 'content-panel',
                        hasApi: true,
                        apiId: 'content-panel',
                        hasExamples: false,
                        isNew: this.expiresAt('2025-08-29')
                    },
                    {
                        id: 'core',
                        name: {
                            ru: 'Core',
                            en: 'Core'
                        },
                        svgPreview: '',
                        hasApi: true,
                        apiId: 'core',
                        hasExamples: false,
                        isNew: this.expiresAt('2025-05-04')
                    },
                    {
                        id: 'datepicker',
                        name: {
                            ru: 'Datepicker',
                            en: 'Datepicker'
                        },
                        svgPreview: 'datepicker',
                        hasApi: true,
                        apiId: 'datepicker',
                        hasExamples: false
                    },
                    {
                        id: 'divider',
                        name: {
                            ru: 'Divider',
                            en: 'Divider'
                        },
                        svgPreview: 'divider',
                        hasApi: true,
                        apiId: 'divider',
                        hasExamples: false
                    },
                    {
                        id: 'dl',
                        name: {
                            ru: 'Description list',
                            en: 'Description list'
                        },
                        svgPreview: 'description list',
                        hasApi: true,
                        apiId: 'dl',
                        hasExamples: false
                    },
                    {
                        id: 'dropdown',
                        name: {
                            ru: 'Dropdown',
                            en: 'Dropdown'
                        },
                        svgPreview: 'dropdown',
                        hasApi: true,
                        apiId: 'dropdown',
                        hasExamples: false
                    },
                    {
                        id: 'empty-state',
                        name: {
                            ru: 'Empty state',
                            en: 'Empty state'
                        },
                        svgPreview: 'empty-state',
                        hasApi: true,
                        apiId: 'empty-state',
                        hasExamples: false
                    },
                    {
                        id: 'icon',
                        name: {
                            ru: 'Icon',
                            en: 'Icon'
                        },
                        svgPreview: 'icons',
                        hasApi: true,
                        apiId: 'icon',
                        hasExamples: false
                    },
                    {
                        id: 'icon-item',
                        name: {
                            ru: 'Icon Item',
                            en: 'Icon Item'
                        },
                        svgPreview: 'icon-item',
                        hasApi: true,
                        apiId: 'icon',
                        hasExamples: false
                    },
                    {
                        id: 'input',
                        name: {
                            ru: 'Input',
                            en: 'Input'
                        },
                        svgPreview: 'input',
                        hasApi: true,
                        apiId: 'input',
                        hasExamples: true
                    },
                    {
                        id: 'file-upload',
                        name: {
                            ru: 'File upload',
                            en: 'File upload'
                        },
                        svgPreview: 'file upload',
                        hasApi: true,
                        apiId: 'file-upload',
                        hasExamples: true
                    },
                    {
                        id: 'filter-bar',
                        name: {
                            ru: 'Filter Bar',
                            en: 'Filter Bar'
                        },
                        svgPreview: 'filter-bar',
                        hasApi: true,
                        apiId: 'filter-bar',
                        hasExamples: true
                    },
                    {
                        id: 'form-field',
                        name: {
                            ru: 'Form field',
                            en: 'Form field'
                        },
                        svgPreview: 'form-field',
                        hasApi: true,
                        apiId: 'form-field',
                        isNew: this.expiresAt('2025-07-26'),
                        hasExamples: false
                    },
                    {
                        id: 'experimental-form-field',
                        name: {
                            ru: 'Form field (experimental)',
                            en: 'Form field (experimental)'
                        },
                        svgPreview: 'form-field',
                        hasApi: true,
                        apiId: 'experimental-form-field',
                        hasExamples: false
                    },
                    {
                        id: 'layout-flex',
                        name: {
                            ru: 'Layout flex',
                            en: 'Layout flex'
                        },
                        svgPreview: 'layout flex',
                        hasApi: false,
                        hasExamples: false
                    },
                    {
                        id: 'link',
                        name: {
                            ru: 'Link',
                            en: 'Link'
                        },
                        svgPreview: 'link',
                        hasApi: true,
                        apiId: 'link',
                        hasExamples: false
                    },
                    {
                        id: 'list',
                        name: {
                            ru: 'List',
                            en: 'List'
                        },
                        svgPreview: 'list',
                        hasApi: true,
                        apiId: 'list',
                        hasExamples: false
                    },
                    {
                        id: 'loader-overlay',
                        name: {
                            ru: 'Overlay',
                            en: 'Overlay'
                        },
                        svgPreview: 'overlay',
                        hasApi: true,
                        apiId: 'loader-overlay',
                        hasExamples: false
                    },
                    {
                        id: 'markdown',
                        name: {
                            ru: 'Markdown',
                            en: 'Markdown'
                        },
                        svgPreview: 'markdown',
                        hasApi: true,
                        apiId: 'markdown',
                        hasExamples: true
                    },
                    {
                        id: 'modal',
                        name: {
                            ru: 'Modal',
                            en: 'Modal'
                        },
                        svgPreview: 'modal',
                        hasApi: true,
                        apiId: 'modal',
                        hasExamples: true
                    },
                    {
                        id: 'navbar',
                        name: {
                            ru: 'Navbar',
                            en: 'Navbar'
                        },
                        svgPreview: 'navbar',
                        hasApi: true,
                        apiId: 'navbar',
                        hasExamples: false
                    },
                    {
                        id: 'overflow-items',
                        name: {
                            ru: 'Overflow items',
                            en: 'Overflow items'
                        },
                        hasApi: true,
                        apiId: 'overflow-items',
                        hasExamples: false
                    },
                    {
                        id: 'popover',
                        name: {
                            ru: 'Popover',
                            en: 'Popover'
                        },
                        svgPreview: 'popover',
                        hasApi: true,
                        apiId: 'popover',
                        hasExamples: true
                    },
                    {
                        id: 'progress-bar',
                        name: {
                            ru: 'Progress bar',
                            en: 'Progress bar'
                        },
                        svgPreview: 'progress-bar',
                        hasApi: true,
                        apiId: 'progress-bar',
                        hasExamples: false
                    },
                    {
                        id: 'progress-spinner',
                        name: {
                            ru: 'Progress spinner',
                            en: 'Progress spinner'
                        },
                        svgPreview: 'progress-spinner',
                        hasApi: true,
                        apiId: 'progress-spinner',
                        hasExamples: false
                    },
                    {
                        id: 'radio',
                        name: {
                            ru: 'Radio',
                            en: 'Radio'
                        },
                        svgPreview: 'radio',
                        hasApi: true,
                        apiId: 'radio',
                        hasExamples: false
                    },
                    {
                        id: 'scrollbar',
                        name: {
                            ru: 'Scrollbar',
                            en: 'Scrollbar'
                        },
                        svgPreview: 'scrollbar',
                        hasApi: true,
                        apiId: 'scrollbar',
                        hasExamples: true
                    },
                    {
                        id: 'select',
                        name: {
                            ru: 'Select',
                            en: 'Select'
                        },
                        svgPreview: 'select',
                        hasApi: true,
                        apiId: 'select',
                        hasExamples: true
                    },
                    {
                        id: 'sidebar',
                        name: {
                            ru: 'Sidebar',
                            en: 'Sidebar'
                        },
                        svgPreview: 'sidebar',
                        hasApi: true,
                        apiId: 'sidebar',
                        hasExamples: true,
                        isNew: this.expiresAt('2025-06-16')
                    },
                    {
                        id: 'sidepanel',
                        name: {
                            ru: 'Sidepanel',
                            en: 'Sidepanel'
                        },
                        svgPreview: 'sidepanel',
                        hasApi: true,
                        apiId: 'sidepanel',
                        hasExamples: false
                    },
                    {
                        id: 'splitter',
                        name: {
                            ru: 'Splitter',
                            en: 'Splitter'
                        },
                        svgPreview: 'splitter',
                        hasApi: true,
                        apiId: 'splitter',
                        hasExamples: false
                    },
                    {
                        id: 'table',
                        name: {
                            ru: 'Table',
                            en: 'Table'
                        },
                        svgPreview: 'table',
                        hasApi: true,
                        apiId: 'table',
                        hasExamples: false
                    },
                    {
                        id: 'tabs',
                        name: {
                            ru: 'Tabs',
                            en: 'Tabs'
                        },
                        svgPreview: 'tabs',
                        hasApi: true,
                        apiId: 'tabs',
                        hasExamples: true
                    },
                    {
                        id: 'tag',
                        name: {
                            ru: 'Tag',
                            en: 'Tag'
                        },
                        svgPreview: 'tags',
                        hasApi: true,
                        apiId: 'tags',
                        hasExamples: false
                    },
                    {
                        id: 'tag-autocomplete',
                        name: {
                            ru: 'Tag autocomplete',
                            en: 'Tag autocomplete'
                        },
                        svgPreview: 'tags autocomplete',
                        hasApi: true,
                        apiId: 'tags',
                        hasExamples: true
                    },
                    {
                        id: 'tag-input',
                        name: {
                            ru: 'Tag input',
                            en: 'Tag input'
                        },
                        svgPreview: 'tags input',
                        hasApi: true,
                        apiId: 'tags',
                        hasExamples: true
                    },
                    {
                        id: 'tag-list',
                        name: {
                            ru: 'Tag list',
                            en: 'Tag list'
                        },
                        svgPreview: 'tags list',
                        hasApi: true,
                        apiId: 'tags',
                        hasExamples: false
                    },
                    {
                        id: 'textarea',
                        name: {
                            ru: 'Textarea',
                            en: 'Textarea'
                        },
                        svgPreview: 'textarea',
                        hasApi: true,
                        apiId: 'textarea',
                        hasExamples: false
                    },
                    {
                        id: 'timepicker',
                        name: {
                            ru: 'Timepicker',
                            en: 'Timepicker'
                        },
                        svgPreview: 'timepicker',
                        hasApi: true,
                        apiId: 'timepicker',
                        hasExamples: false
                    },
                    {
                        id: 'timezone',
                        name: {
                            ru: 'Timezone',
                            en: 'Timezone'
                        },
                        svgPreview: 'timezone',
                        hasApi: true,
                        apiId: 'timezone',
                        hasExamples: false
                    },
                    {
                        id: 'title',
                        name: {
                            ru: 'Title',
                            en: 'Title'
                        },
                        hasApi: true,
                        apiId: 'title',
                        hasExamples: false
                    },
                    {
                        id: 'toast',
                        name: {
                            ru: 'Toast',
                            en: 'Toast'
                        },
                        svgPreview: 'toast',
                        hasApi: true,
                        apiId: 'toast',
                        hasExamples: true
                    },
                    {
                        id: 'toggle',
                        name: {
                            ru: 'Toggle',
                            en: 'Toggle'
                        },
                        svgPreview: 'toggle',
                        hasApi: true,
                        apiId: 'toggle',
                        hasExamples: false
                    },
                    {
                        id: 'tooltip',
                        name: {
                            ru: 'Tooltip',
                            en: 'Tooltip'
                        },
                        svgPreview: 'tooltip',
                        hasApi: true,
                        apiId: 'tooltip',
                        hasExamples: true
                    },
                    {
                        id: 'top-bar',
                        name: {
                            ru: 'Topbar',
                            en: 'Topbar'
                        },
                        svgPreview: 'top-bar',
                        hasApi: true,
                        apiId: 'top-bar',
                        hasExamples: false
                    },
                    {
                        id: 'tree',
                        name: {
                            ru: 'Tree',
                            en: 'Tree'
                        },
                        svgPreview: 'tree',
                        hasApi: true,
                        apiId: 'tree',
                        hasExamples: true
                    },
                    {
                        id: 'tree-select',
                        name: {
                            ru: 'Tree select',
                            en: 'Tree select'
                        },
                        svgPreview: 'tree-select',
                        hasApi: true,
                        apiId: 'tree-select',
                        hasExamples: true
                    }
                ]
            }
        ],
        [DocsDocStructureCategoryId.Other]: [
            {
                id: DocsDocStructureCategoryId.Other,
                name: {
                    ru: 'Другое',
                    en: 'Other'
                },
                isPreviewed: true,
                items: [
                    {
                        id: 'date-formatter',
                        name: {
                            ru: 'Date formatter',
                            en: 'Date formatter'
                        },
                        svgPreview: 'date',
                        hasApi: false,
                        apiId: 'date-formatter',
                        hasExamples: true
                    },
                    {
                        id: 'filesize-formatter',
                        name: {
                            ru: 'Filesize formatter',
                            en: 'Filesize formatter'
                        },
                        svgPreview: 'formatter-filesize',
                        hasApi: false,
                        hasExamples: false,
                        isNew: this.expiresAt('2025-06-08')
                    },
                    {
                        id: 'forms',
                        name: {
                            ru: 'Forms',
                            en: 'Forms'
                        },
                        svgPreview: 'forms',
                        hasApi: false,
                        apiId: 'forms',
                        hasExamples: false
                    },
                    {
                        id: 'number-formatter',
                        name: {
                            ru: 'Number formatter',
                            en: 'Number formatter'
                        },
                        svgPreview: 'number',
                        hasApi: false,
                        apiId: 'number-formatter',
                        hasExamples: false
                    },
                    {
                        id: 'validation',
                        name: {
                            ru: 'Validation',
                            en: 'Validation'
                        },
                        svgPreview: 'validation',
                        hasApi: false,
                        hasExamples: false,
                        isNew: this.expiresAt('2025-08-17')
                    }
                ]
            }
        ],
        [DocsDocStructureCategoryId.Icons]: [
            {
                id: DocsDocStructureCategoryId.Icons,
                name: {
                    ru: 'Иконки',
                    en: 'Icons'
                },
                isPreviewed: false,
                items: []
            }
        ],
        [DocsDocStructureCategoryId.CDK]: [
            {
                id: DocsDocStructureCategoryId.CDK,
                name: {
                    ru: 'CDK',
                    en: 'CDK'
                },
                isPreviewed: false,
                items: [
                    {
                        id: 'a11y',
                        name: {
                            ru: 'Key managers',
                            en: 'Key managers'
                        },
                        hasApi: true,
                        apiId: 'a11y',
                        hasExamples: false
                    },
                    {
                        id: 'keycodes',
                        name: {
                            ru: 'Keycodes',
                            en: 'Keycodes'
                        },
                        hasApi: true,
                        apiId: 'keycodes',
                        hasExamples: false
                    }
                ]
            }
        ]
    });

    private static allMain = this.structure[DocsDocStructureCategoryId.Main].flatMap((category) => category.items);

    private static allComponents = this.structure[DocsDocStructureCategoryId.Components].flatMap(
        (category) => category.items
    );

    private static allOther = this.structure[DocsDocStructureCategoryId.Other].flatMap((category) => category.items);

    private static allIcons = this.structure[DocsDocStructureCategoryId.Icons].flatMap((category) => category.items);

    private static allCdk = this.structure[DocsDocStructureCategoryId.CDK].flatMap((category) => category.items);

    private static allItems = [
        this.allMain,
        this.allComponents,
        this.allOther,
        this.allIcons,
        this.allCdk
    ].flat();

    private static allCategories = [
        this.structure[DocsDocStructureCategoryId.Main],
        this.structure[DocsDocStructureCategoryId.Components],
        this.structure[DocsDocStructureCategoryId.Other],
        this.structure[DocsDocStructureCategoryId.Icons],
        this.structure[DocsDocStructureCategoryId.CDK]
    ].flat();

    static getCategories(categoryId?: DocsDocStructureCategoryId): DocsDocStructureCategory[] {
        if (categoryId) return this.structure[categoryId];

        return this.allCategories;
    }

    static getItemsByCategoryId(categoryId: DocsDocStructureCategoryId): DocsDocStructureCategoryItem[] {
        switch (categoryId) {
            case DocsDocStructureCategoryId.Components: {
                return this.allComponents;
            }
            case DocsDocStructureCategoryId.CDK: {
                return this.allCdk;
            }
            case DocsDocStructureCategoryId.Main: {
                return this.allMain;
            }
            case DocsDocStructureCategoryId.Other: {
                return this.allOther;
            }
            case DocsDocStructureCategoryId.Icons: {
                return this.allIcons;
            }
            default: {
                return [];
            }
        }
    }

    static getItems(): DocsDocStructureCategoryItem[] {
        return this.allItems;
    }

    static getItemById(id: string, categoryId: string): DocsDocStructureCategoryItem | undefined {
        if (!id) return undefined;

        return this.allItems.find((item) => item.id === id && item.categoryId === categoryId);
    }

    static getCategoryById(id: string): DocsDocStructureCategory | undefined {
        return this.allCategories.find((category) => category.id === id);
    }

    private static makeStructure(
        structure: Record<DocsDocStructureCategoryId, DocsDocStructureCategory[]>
    ): Record<DocsDocStructureCategoryId, DocsDocStructureCategory[]> {
        Object.values(DocsDocStructureCategoryId).forEach((categoryId) => {
            structure[categoryId].forEach((category) => {
                category.items.forEach((item) => (item.categoryId = category.id));
            });
        });

        return structure;
    }

    private static expiresAt(expiresAt: string): boolean {
        const createdDate = DateTime.fromISO(expiresAt);

        if (!createdDate.isValid) {
            throw new Error(createdDate.invalidReason);
        }

        return createdDate.diffNow('days').days > 0;
    }
}
