import { DateTime } from 'luxon';
import { DocsLocale } from './constants/locale';

export enum DocsStructureItemId {
    // Main
    Installation = 'installation',
    Versioning = 'versioning',
    DirectoryStructure = 'directory-structure',
    Theming = 'theming',
    Typography = 'typography',
    DesignTokens = 'design-tokens',
    Schematics = 'schematics',
    Migration = 'migration',
    // Components
    Accordion = 'accordion',
    ActionsPanel = 'actions-panel',
    AppSwitcher = 'app-switcher',
    AgGrid = 'ag-grid',
    Alert = 'alert',
    Autocomplete = 'autocomplete',
    Badge = 'badge',
    Breadcrumbs = 'breadcrumbs',
    Button = 'button',
    ButtonToggle = 'button-toggle',
    Checkbox = 'checkbox',
    ClampedText = 'clamped-text',
    CodeBlock = 'code-block',
    ContentPanel = 'content-panel',
    Core = 'core',
    Datepicker = 'datepicker',
    Divider = 'divider',
    Dl = 'dl',
    Dropdown = 'dropdown',
    DynamicTranslation = 'dynamic-translation',
    EmptyState = 'empty-state',
    Icon = 'icon',
    IconItem = 'icon-item',
    InlineEdit = 'inline-edit',
    Input = 'input',
    FileUpload = 'file-upload',
    FilterBar = 'filter-bar',
    FormField = 'form-field',
    LayoutFlex = 'layout-flex',
    Link = 'link',
    List = 'list',
    LoaderOverlay = 'loader-overlay',
    Markdown = 'markdown',
    Modal = 'modal',
    Navbar = 'navbar',
    NavbarIc = 'navbar-ic',
    NotificationCenter = 'notification-center',
    OverflowItems = 'overflow-items',
    Popover = 'popover',
    ProgressBar = 'progress-bar',
    ProgressSpinner = 'progress-spinner',
    Radio = 'radio',
    Resizer = 'resizer',
    Scrollbar = 'scrollbar',
    Select = 'select',
    SearchExpandable = 'search-expandable',
    Sidebar = 'sidebar',
    Sidepanel = 'sidepanel',
    Splitter = 'splitter',
    SplitButton = 'split-button',
    Table = 'table',
    Tabs = 'tabs',
    Tag = 'tag',
    TagAutocomplete = 'tag-autocomplete',
    TagInput = 'tag-input',
    TagList = 'tag-list',
    Textarea = 'textarea',
    Timepicker = 'timepicker',
    TimeRange = 'time-range',
    Timezone = 'timezone',
    Title = 'title',
    Toast = 'toast',
    Toggle = 'toggle',
    Tooltip = 'tooltip',
    TopBar = 'top-bar',
    Tree = 'tree',
    TreeSelect = 'tree-select',
    Username = 'username',
    // Other
    DateFormatter = 'date-formatter',
    FilesizeFormatter = 'filesize-formatter',
    Forms = 'forms',
    NumberFormatter = 'number-formatter',
    Validation = 'validation',
    // CDK
    A11y = 'a11y',
    Keycodes = 'keycodes'
}

export type DocsStructureItem = {
    id: DocsStructureItemId;
    name: Record<DocsLocale, string>;
    hasApi: boolean;
    hasExamples: boolean;
    isGuide?: boolean;
    apiId?: string;
    svgPreview?: string;
    /**
     * NOTE! Do not edit manually, this property is autogenerated.
     */
    categoryId?: DocsStructureCategoryId;
    /**
     * Indicates whether documentation item as "new".
     * Determined by comparing the current date with expiration date.
     */
    isNew?: boolean;
};

export enum DocsStructureCategoryId {
    Main = 'main',
    Components = 'components',
    Other = 'other',
    Icons = 'icons',
    CDK = 'cdk'
}

export type DocsStructureCategory = {
    id: DocsStructureCategoryId;
    name: Record<DocsLocale, string>;
    items: DocsStructureItem[];
    isPreviewed?: boolean;
};

export enum DocsStructureItemTab {
    Overview = 'overview',
    Api = 'api',
    Examples = 'examples'
}

export enum DocsStructureTokensTab {
    Colors = 'colors',
    Typography = 'typography',
    Shadows = 'shadows',
    BorderRadius = 'border-radius',
    Sizes = 'sizes',
    Palette = 'palette'
}

export type DocsStructure = Record<DocsStructureCategoryId, DocsStructureCategory[]>;

const makeStructure = (structure: DocsStructure): DocsStructure => {
    Object.values(DocsStructureCategoryId).forEach((categoryId) => {
        structure[categoryId].forEach((category) => {
            category.items.forEach((item) => (item.categoryId = category.id));
        });
    });

    return structure;
};

const expiresAt = (expiresAt: string): boolean => {
    const createdDate = DateTime.fromISO(expiresAt);

    if (!createdDate.isValid) {
        throw new Error(createdDate.invalidReason);
    }

    return createdDate.diffNow('days').days > 0;
};

const structure: DocsStructure = makeStructure({
    [DocsStructureCategoryId.Main]: [
        {
            id: DocsStructureCategoryId.Main,
            name: {
                ru: 'Основное',
                en: 'Main'
            },
            isPreviewed: true,
            items: [
                {
                    id: DocsStructureItemId.Installation,
                    name: {
                        ru: 'Установка',
                        en: 'Installation'
                    },
                    svgPreview: 'install',
                    isGuide: true,
                    hasApi: false,
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Versioning,
                    name: {
                        ru: 'Версионирование',
                        en: 'Versioning'
                    },
                    svgPreview: 'versioning',
                    isGuide: true,
                    hasApi: false,
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.DirectoryStructure,
                    name: {
                        ru: 'Структура каталогов',
                        en: 'Directory structure'
                    },
                    svgPreview: 'catalog structure',
                    isGuide: true,
                    hasApi: false,
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Theming,
                    name: {
                        ru: 'Темизация',
                        en: 'Theming'
                    },
                    svgPreview: 'themes',
                    isGuide: true,
                    hasApi: false,
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Typography,
                    name: {
                        ru: 'Типографика',
                        en: 'Typography'
                    },
                    svgPreview: 'typography',
                    hasApi: false,
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.DesignTokens,
                    name: {
                        ru: 'Дизайн-токены',
                        en: 'Design tokens'
                    },
                    svgPreview: 'tokens',
                    hasApi: false,
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Schematics,
                    name: {
                        ru: 'Схематики',
                        en: 'Schematics'
                    },
                    svgPreview: 'schematics',
                    hasApi: false,
                    hasExamples: false
                },

                {
                    id: DocsStructureItemId.Migration,
                    name: {
                        ru: 'Гайды по миграции',
                        en: 'Migration guides'
                    },
                    svgPreview: '',
                    hasApi: false,
                    hasExamples: false,
                    isNew: expiresAt('2025-07-13')
                }
            ]
        }
    ],
    [DocsStructureCategoryId.Components]: [
        {
            id: DocsStructureCategoryId.Components,
            name: {
                ru: 'Компоненты',
                en: 'Components'
            },
            isPreviewed: true,
            items: [
                {
                    id: DocsStructureItemId.Accordion,
                    name: {
                        ru: 'Accordion',
                        en: 'Accordion'
                    },
                    svgPreview: 'accordion',
                    hasApi: true,
                    apiId: 'accordion',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.ActionsPanel,
                    name: {
                        ru: 'Actions panel',
                        en: 'Actions panel'
                    },
                    svgPreview: 'actions-panel',
                    hasApi: true,
                    apiId: 'actions-panel',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.AppSwitcher,
                    name: {
                        ru: 'App Switcher',
                        en: 'App Switcher'
                    },
                    svgPreview: 'app-switcher',
                    hasApi: true,
                    apiId: 'app-switcher',
                    hasExamples: false,
                    isNew: expiresAt('2025-10-20')
                },
                {
                    id: DocsStructureItemId.AgGrid,
                    name: {
                        ru: 'AG grid',
                        en: 'AG grid'
                    },
                    svgPreview: 'ag-grid',
                    hasApi: false,
                    hasExamples: false,
                    isNew: expiresAt('2025-05-04')
                },
                {
                    id: DocsStructureItemId.Alert,
                    name: {
                        ru: 'Alert',
                        en: 'Alert'
                    },
                    svgPreview: 'alerts',
                    hasApi: true,
                    apiId: 'alert',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Autocomplete,
                    name: {
                        ru: 'Autocomplete',
                        en: 'Autocomplete'
                    },
                    svgPreview: 'autocomplete',
                    hasApi: true,
                    apiId: 'autocomplete',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Badge,
                    name: {
                        ru: 'Badge',
                        en: 'Badge'
                    },
                    svgPreview: 'badges',
                    hasApi: true,
                    apiId: 'badge',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Breadcrumbs,
                    name: {
                        ru: 'Breadcrumbs',
                        en: 'Breadcrumbs'
                    },
                    svgPreview: 'breadcrumbs',
                    hasApi: true,
                    apiId: 'breadcrumbs',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.Button,
                    name: {
                        ru: 'Button',
                        en: 'Button'
                    },
                    svgPreview: 'button',
                    hasApi: true,
                    apiId: 'button',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.ButtonToggle,
                    name: {
                        ru: 'Button toggle',
                        en: 'Button toggle'
                    },
                    svgPreview: 'button toggle',
                    hasApi: true,
                    apiId: 'button-toggle',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Checkbox,
                    name: {
                        ru: 'Checkbox',
                        en: 'Checkbox'
                    },
                    svgPreview: 'checkbox',
                    hasApi: true,
                    apiId: 'checkbox',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.ClampedText,
                    name: {
                        ru: 'Clamped text',
                        en: 'Clamped text'
                    },
                    svgPreview: 'clamped-text',
                    hasApi: true,
                    apiId: 'clamped-text',
                    hasExamples: false,
                    isNew: expiresAt('2025-08-29')
                },
                {
                    id: DocsStructureItemId.CodeBlock,
                    name: {
                        ru: 'Code block',
                        en: 'Code block'
                    },
                    svgPreview: 'code-block',
                    hasApi: true,
                    apiId: 'code-block',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.ContentPanel,
                    name: {
                        ru: 'Content panel',
                        en: 'Content panel'
                    },
                    svgPreview: 'content-panel',
                    hasApi: true,
                    apiId: 'content-panel',
                    hasExamples: false,
                    isNew: expiresAt('2025-08-29')
                },
                {
                    id: DocsStructureItemId.Core,
                    name: {
                        ru: 'Core',
                        en: 'Core'
                    },
                    svgPreview: 'core',
                    hasApi: true,
                    apiId: 'core',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Datepicker,
                    name: {
                        ru: 'Datepicker',
                        en: 'Datepicker'
                    },
                    svgPreview: 'datepicker',
                    hasApi: true,
                    apiId: 'datepicker',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Divider,
                    name: {
                        ru: 'Divider',
                        en: 'Divider'
                    },
                    svgPreview: 'divider',
                    hasApi: true,
                    apiId: 'divider',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Dl,
                    name: {
                        ru: 'Description list',
                        en: 'Description list'
                    },
                    svgPreview: 'description list',
                    hasApi: true,
                    apiId: 'dl',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Dropdown,
                    name: {
                        ru: 'Dropdown',
                        en: 'Dropdown'
                    },
                    svgPreview: 'dropdown',
                    hasApi: true,
                    apiId: 'dropdown',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.DynamicTranslation,
                    name: {
                        ru: 'Dynamic translation',
                        en: 'Dynamic translation'
                    },
                    svgPreview: 'dynamic-translation',
                    hasApi: true,
                    apiId: 'dynamic-translation',
                    hasExamples: true,
                    isNew: expiresAt('2025-09-14')
                },
                {
                    id: DocsStructureItemId.EmptyState,
                    name: {
                        ru: 'Empty state',
                        en: 'Empty state'
                    },
                    svgPreview: 'empty-state',
                    hasApi: true,
                    apiId: 'empty-state',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Icon,
                    name: {
                        ru: 'Icon',
                        en: 'Icon'
                    },
                    svgPreview: 'icons',
                    hasApi: true,
                    apiId: 'icon',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.IconItem,
                    name: {
                        ru: 'Icon Item',
                        en: 'Icon Item'
                    },
                    svgPreview: 'icon-item',
                    hasApi: true,
                    apiId: 'icon',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.InlineEdit,
                    name: {
                        ru: 'Inline edit',
                        en: 'Inline edit'
                    },
                    svgPreview: 'inline-edit',
                    hasApi: true,
                    apiId: 'inline-edit',
                    hasExamples: true,
                    isNew: expiresAt('2025-10-15')
                },
                {
                    id: DocsStructureItemId.Input,
                    name: {
                        ru: 'Input',
                        en: 'Input'
                    },
                    svgPreview: 'input',
                    hasApi: true,
                    apiId: 'input',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.FileUpload,
                    name: {
                        ru: 'File upload',
                        en: 'File upload'
                    },
                    svgPreview: 'file upload',
                    hasApi: true,
                    apiId: 'file-upload',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.FilterBar,
                    name: {
                        ru: 'Filter Bar',
                        en: 'Filter Bar'
                    },
                    svgPreview: 'filter-bar',
                    hasApi: true,
                    apiId: 'filter-bar',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.FormField,
                    name: {
                        ru: 'Form field',
                        en: 'Form field'
                    },
                    svgPreview: 'form-field',
                    hasApi: true,
                    apiId: 'form-field',
                    isNew: expiresAt('2025-07-26'),
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.LayoutFlex,
                    name: {
                        ru: 'Layout flex',
                        en: 'Layout flex'
                    },
                    svgPreview: 'layout flex',
                    hasApi: false,
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Link,
                    name: {
                        ru: 'Link',
                        en: 'Link'
                    },
                    svgPreview: 'link',
                    hasApi: true,
                    apiId: 'link',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.List,
                    name: {
                        ru: 'List',
                        en: 'List'
                    },
                    svgPreview: 'list',
                    hasApi: true,
                    apiId: 'list',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.LoaderOverlay,
                    name: {
                        ru: 'Overlay',
                        en: 'Overlay'
                    },
                    svgPreview: 'overlay',
                    hasApi: true,
                    apiId: 'loader-overlay',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Markdown,
                    name: {
                        ru: 'Markdown',
                        en: 'Markdown'
                    },
                    svgPreview: 'markdown',
                    hasApi: true,
                    apiId: 'markdown',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.Modal,
                    name: {
                        ru: 'Modal',
                        en: 'Modal'
                    },
                    svgPreview: 'modal',
                    hasApi: true,
                    apiId: 'modal',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.Navbar,
                    name: {
                        ru: 'Navbar',
                        en: 'Navbar'
                    },
                    svgPreview: 'navbar',
                    hasApi: true,
                    apiId: 'navbar',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.NavbarIc,
                    name: {
                        ru: 'Infosec Navbar',
                        en: 'Infosec Navbar'
                    },
                    svgPreview: 'navbar-ic',
                    hasApi: true,
                    apiId: 'navbar-ic',
                    hasExamples: false,
                    isNew: expiresAt('2025-09-20')
                },
                {
                    id: DocsStructureItemId.NotificationCenter,
                    name: {
                        ru: 'Notification Center',
                        en: 'Notification Center'
                    },
                    svgPreview: 'notification-center',
                    hasApi: true,
                    apiId: 'notification-center',
                    hasExamples: false,
                    isNew: expiresAt('2025-11-10')
                },
                {
                    id: DocsStructureItemId.OverflowItems,
                    name: {
                        ru: 'Overflow items',
                        en: 'Overflow items'
                    },
                    hasApi: true,
                    apiId: 'overflow-items',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Popover,
                    name: {
                        ru: 'Popover',
                        en: 'Popover'
                    },
                    svgPreview: 'popover',
                    hasApi: true,
                    apiId: 'popover',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.ProgressBar,
                    name: {
                        ru: 'Progress bar',
                        en: 'Progress bar'
                    },
                    svgPreview: 'progress-bar',
                    hasApi: true,
                    apiId: 'progress-bar',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.ProgressSpinner,
                    name: {
                        ru: 'Progress spinner',
                        en: 'Progress spinner'
                    },
                    svgPreview: 'progress-spinner',
                    hasApi: true,
                    apiId: 'progress-spinner',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Radio,
                    name: {
                        ru: 'Radio',
                        en: 'Radio'
                    },
                    svgPreview: 'radio',
                    hasApi: true,
                    apiId: 'radio',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Resizer,
                    name: {
                        ru: 'Resizer',
                        en: 'Resizer'
                    },
                    svgPreview: 'resizer',
                    hasApi: true,
                    apiId: 'resizer',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Scrollbar,
                    name: {
                        ru: 'Scrollbar',
                        en: 'Scrollbar'
                    },
                    svgPreview: 'scrollbar',
                    hasApi: true,
                    apiId: 'scrollbar',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.Select,
                    name: {
                        ru: 'Select',
                        en: 'Select'
                    },
                    svgPreview: 'select',
                    hasApi: true,
                    apiId: 'select',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.SearchExpandable,
                    name: {
                        ru: 'Search expandable',
                        en: 'Search expandable'
                    },
                    svgPreview: 'search-expandable',
                    hasApi: true,
                    apiId: 'search-expandable',
                    hasExamples: false,
                    isNew: expiresAt('2025-10-10')
                },
                {
                    id: DocsStructureItemId.Sidebar,
                    name: {
                        ru: 'Sidebar',
                        en: 'Sidebar'
                    },
                    svgPreview: 'sidebar',
                    hasApi: true,
                    apiId: 'sidebar',
                    hasExamples: true,
                    isNew: expiresAt('2025-06-16')
                },
                {
                    id: DocsStructureItemId.Sidepanel,
                    name: {
                        ru: 'Sidepanel',
                        en: 'Sidepanel'
                    },
                    svgPreview: 'sidepanel',
                    hasApi: true,
                    apiId: 'sidepanel',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.Splitter,
                    name: {
                        ru: 'Splitter',
                        en: 'Splitter'
                    },
                    svgPreview: 'splitter',
                    hasApi: true,
                    apiId: 'splitter',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.SplitButton,
                    name: {
                        ru: 'Split button',
                        en: 'Split button'
                    },
                    svgPreview: 'split-button',
                    hasApi: true,
                    apiId: 'split-button',
                    hasExamples: false,
                    isNew: expiresAt('2025-10-10')
                },
                {
                    id: DocsStructureItemId.Table,
                    name: {
                        ru: 'Table',
                        en: 'Table'
                    },
                    svgPreview: 'table',
                    hasApi: true,
                    apiId: 'table',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Tabs,
                    name: {
                        ru: 'Tabs',
                        en: 'Tabs'
                    },
                    svgPreview: 'tabs',
                    hasApi: true,
                    apiId: 'tabs',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.Tag,
                    name: {
                        ru: 'Tag',
                        en: 'Tag'
                    },
                    svgPreview: 'tags',
                    hasApi: true,
                    apiId: 'tags',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.TagAutocomplete,
                    name: {
                        ru: 'Tag autocomplete',
                        en: 'Tag autocomplete'
                    },
                    svgPreview: 'tags autocomplete',
                    hasApi: true,
                    apiId: 'tags',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.TagInput,
                    name: {
                        ru: 'Tag input',
                        en: 'Tag input'
                    },
                    svgPreview: 'tags input',
                    hasApi: true,
                    apiId: 'tags',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.TagList,
                    name: {
                        ru: 'Tag list',
                        en: 'Tag list'
                    },
                    svgPreview: 'tags list',
                    hasApi: true,
                    apiId: 'tags',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Textarea,
                    name: {
                        ru: 'Textarea',
                        en: 'Textarea'
                    },
                    svgPreview: 'textarea',
                    hasApi: true,
                    apiId: 'textarea',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Timepicker,
                    name: {
                        ru: 'Timepicker',
                        en: 'Timepicker'
                    },
                    svgPreview: 'timepicker',
                    hasApi: true,
                    apiId: 'timepicker',
                    hasExamples: false
                },

                {
                    id: DocsStructureItemId.TimeRange,
                    name: {
                        ru: 'Time range',
                        en: 'Time range'
                    },
                    hasApi: true,
                    apiId: 'time-range',
                    hasExamples: true,
                    isNew: expiresAt('2025-10-31')
                },
                {
                    id: DocsStructureItemId.Timezone,
                    name: {
                        ru: 'Timezone',
                        en: 'Timezone'
                    },
                    svgPreview: 'timezone',
                    hasApi: true,
                    apiId: 'timezone',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Title,
                    name: {
                        ru: 'Title',
                        en: 'Title'
                    },
                    hasApi: true,
                    apiId: 'title',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Toast,
                    name: {
                        ru: 'Toast',
                        en: 'Toast'
                    },
                    svgPreview: 'toast',
                    hasApi: true,
                    apiId: 'toast',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.Toggle,
                    name: {
                        ru: 'Toggle',
                        en: 'Toggle'
                    },
                    svgPreview: 'toggle',
                    hasApi: true,
                    apiId: 'toggle',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Tooltip,
                    name: {
                        ru: 'Tooltip',
                        en: 'Tooltip'
                    },
                    svgPreview: 'tooltip',
                    hasApi: true,
                    apiId: 'tooltip',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.TopBar,
                    name: {
                        ru: 'Topbar',
                        en: 'Topbar'
                    },
                    svgPreview: 'top-bar',
                    hasApi: true,
                    apiId: 'top-bar',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Tree,
                    name: {
                        ru: 'Tree',
                        en: 'Tree'
                    },
                    svgPreview: 'tree',
                    hasApi: true,
                    apiId: 'tree',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.TreeSelect,
                    name: {
                        ru: 'Tree select',
                        en: 'Tree select'
                    },
                    svgPreview: 'tree-select',
                    hasApi: true,
                    apiId: 'tree-select',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.Username,
                    name: {
                        ru: 'Username',
                        en: 'Username'
                    },
                    hasApi: true,
                    apiId: 'username',
                    hasExamples: false,
                    isNew: expiresAt('2025-08-24')
                }
            ]
        }
    ],
    [DocsStructureCategoryId.Other]: [
        {
            id: DocsStructureCategoryId.Other,
            name: {
                ru: 'Другое',
                en: 'Other'
            },
            isPreviewed: true,
            items: [
                {
                    id: DocsStructureItemId.DateFormatter,
                    name: {
                        ru: 'Date formatter',
                        en: 'Date formatter'
                    },
                    svgPreview: 'date',
                    hasApi: false,
                    apiId: 'date-formatter',
                    hasExamples: true
                },
                {
                    id: DocsStructureItemId.FilesizeFormatter,
                    name: {
                        ru: 'Filesize formatter',
                        en: 'Filesize formatter'
                    },
                    svgPreview: 'formatter-filesize',
                    hasApi: false,
                    hasExamples: false,
                    isNew: expiresAt('2025-06-08')
                },
                {
                    id: DocsStructureItemId.Forms,
                    name: {
                        ru: 'Forms',
                        en: 'Forms'
                    },
                    svgPreview: 'forms',
                    hasApi: false,
                    apiId: 'forms',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.NumberFormatter,
                    name: {
                        ru: 'Number formatter',
                        en: 'Number formatter'
                    },
                    svgPreview: 'number',
                    hasApi: false,
                    apiId: 'number-formatter',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Validation,
                    name: {
                        ru: 'Validation',
                        en: 'Validation'
                    },
                    svgPreview: 'validation',
                    hasApi: false,
                    hasExamples: false,
                    isNew: expiresAt('2025-08-17')
                }
            ]
        }
    ],
    [DocsStructureCategoryId.Icons]: [
        {
            id: DocsStructureCategoryId.Icons,
            name: {
                ru: 'Иконки',
                en: 'Icons'
            },
            isPreviewed: false,
            items: []
        }
    ],
    [DocsStructureCategoryId.CDK]: [
        {
            id: DocsStructureCategoryId.CDK,
            name: {
                ru: 'CDK',
                en: 'CDK'
            },
            isPreviewed: false,
            items: [
                {
                    id: DocsStructureItemId.A11y,
                    name: {
                        ru: 'Key managers',
                        en: 'Key managers'
                    },
                    hasApi: true,
                    apiId: 'a11y',
                    hasExamples: false
                },
                {
                    id: DocsStructureItemId.Keycodes,
                    name: {
                        ru: 'Keycodes',
                        en: 'Keycodes'
                    },
                    hasApi: true,
                    apiId: 'keycodes',
                    hasExamples: false
                }
            ]
        }
    ]
});

const itemsByCategoryId: Record<DocsStructureCategoryId, DocsStructureItem[]> = Object.values(
    DocsStructureCategoryId
).reduce(
    (result, categoryId) => {
        result[categoryId] = structure[categoryId].flatMap((category) => category.items);

        return result;
    },
    {} as Record<DocsStructureCategoryId, DocsStructureItem[]>
);

const items: DocsStructureItem[] = Object.values(itemsByCategoryId).flat();

const categories: DocsStructureCategory[] = Object.values(structure).flat();

export const docsGetCategories = (): DocsStructureCategory[] => {
    return categories;
};

export const docsGetCategoriesById = (categoryId: DocsStructureCategoryId): DocsStructureCategory[] => {
    return structure[categoryId];
};

export const docsGetItemsByCategoryId = (categoryId: DocsStructureCategoryId): DocsStructureItem[] => {
    return itemsByCategoryId[categoryId];
};

export const docsGetItems = (): DocsStructureItem[] => {
    return items;
};

export const docsGetItemById = (
    itemId: DocsStructureItemId,
    categoryId: DocsStructureCategoryId
): DocsStructureItem | undefined => {
    return items.find((item) => item.id === itemId && item.categoryId === categoryId);
};

export const docsGetCategoryById = (categoryId: DocsStructureCategoryId): DocsStructureCategory | undefined => {
    return categories.find((category) => category.id === categoryId);
};
