name: API

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/workflows/actions/setup-node
      - uses: ./.github/workflows/actions/build-packages
      - run: yarn run check-api
