name: Build

on:
  pull_request:

permissions:
  contents: read # for actions/checkout to read the repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/workflows/actions/setup-node
      - uses: ./.github/workflows/actions/build-packages
      - uses: ./.github/workflows/actions/build-docs
