name: Linters

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/workflows/actions/setup-node
      - run: |
          yarn run cspell --no-progress
          yarn run prettier
          yarn run stylelint --max-warnings=0
          yarn run eslint --max-warnings=0
