name: Linters

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/workflows/actions/setup-node
      - run: |
          yarn run cspell --no-progress
          yarn run prettier
          yarn run stylelint --max-warnings=0
          yarn run eslint --max-warnings=0
