name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/workflows/actions/setup-node
      # Build styles which are required for unit tests
      - run: yarn run styles:build-all
      - run: |
          yarn run unit:components
          yarn run unit:angular-moment-adapter
          yarn run unit:angular-luxon-adapter
          yarn run unit:schematics
          yarn run unit:koobiq-docs
          yarn run unit:api-gen
          yarn run unit:components-experimental
