name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/workflows/actions/setup-node
      # Build styles which are required for unit tests
      - run: yarn run styles:build-all
      - run: |
          yarn run unit:components
          yarn run unit:angular-moment-adapter
          yarn run unit:angular-luxon-adapter
          yarn run unit:schematics
          yarn run unit:koobiq-docs
          yarn run unit:api-gen
          yarn run unit:components-experimental
